### ISSUE TITLE
Change completion API response to a more general form

### ISSUE THREAD

**Issue by Qusic** [ycm-core/ycmd#121]
This seems too specific to YouCompleteMe vim client. Parameters list should not be merged into the function name.

```
{
    "detailed_info": "Foo & operator=( const Foo & )\nFoo & operator=( Foo && )\n",
    "extra_menu_info": "Foo &",
    "insertion_text": "operator=",
    "kind": "FUNCTION",
    "menu_text": "operator=( const Foo & )"
}
```

My desired completions look like:

```
{
    "kind": "function",
    "name": "myFun",
    "parameters": [{
        "type": "int",
        "name": "number"
    }, {
        "type": "std::string",
        "name": "text"
    }],
    "return_type": "Foo &",
    "docstring": "..."
}

{
    "kind": "variable",
    "name": "a",
    "type": "int"
}
```

So that clients decide what the insertion text, menu info or whatever is, and clients with different capabilities can all have a chance to make the best completion experience.
I am working on the Atom client and such completions can be used to build snippets and provide function completions with parameter placeholders.

**Comment by Valloric** [comment]
Oh I agree with you completely. `detailed_info` is meant to be a suggestion. We should totally be returning a list of all the parameters (and function overloads, which are currently missing) in a structured format.

More work needs to be put into making this happen and I haven't had the time to do it so far.

**Comment by Qusic** [comment]
Considering different argument formats for functions, templates, objc methods and even functions in other languages, my proposal in the original post seems to make things too complicated.
Do you have any ideas for a simple and flexible completion representation?

**Comment by Valloric** [comment]
I don't currently have a specific design in mind beyond "we need to return structured data for parameters/overloads" so that stuff is broken out and that clients can pick and choose which data they want without having to parse detailed_info.

**Comment by ptrv** [comment]
This change would be really useful since in `emacs-ycmd` we do parsing and text manipulation of detailed_info, to separate the parameters and return type. A more generic API would be really appreciated.

**Comment by sanwv** [comment]
how about return a snippet?

```
{
    "snippet": "myFun(${1:int},${2:string}){\n return ${3:Foo}\n}",
   ....
}
```

**Comment by richard1122** [comment]
Is there going to be any updates about this? 
Split parameters out would be great.

Also it's acceptable to just add parameters for backward compatible.

**Comment by puremourning** [comment]
The new signature-help support will supersede this, I think.

Also we can't really break the API in this way
