### ISSUE TITLE
Some problems in installing the ycm

### ISSUE THREAD

**Issue by lsli0116** [ycm-core/ycmd#1291]

**Comment by lsli0116** [comment]
I type this command in the terminal : git submodule update --init --recursive
And the terminal said as Follow:
Cloning into '/Users/lsli/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/go/src/golang.org/x/tools'...
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Operation timed out
fatal: clone of 'https://go.googlesource.com/tools' into submodule path '/Users/lsli/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/go/src/golang.org/x/tools' failed
Failed to clone 'third_party/go/src/golang.org/x/tools'. Retry scheduled
Cloning into '/Users/lsli/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/go/src/golang.org/x/tools'...
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Operation timed out
fatal: clone of 'https://go.googlesource.com/tools' into submodule path '/Users/lsli/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/go/src/golang.org/x/tools' failed
Failed to clone 'third_party/go/src/golang.org/x/tools' a second time, aborting
Failed to recurse into submodule path 'third_party/ycmd'

How can I deal with it?

**Comment by puremourning** [comment]
Dup
