### ISSUE TITLE
Changing class attribute does not mark errors in cpp file

### ISSUE THREAD

**Issue by dpknesek** [ycm-core/ycmd#1298]
I am running nvim with clangd.

I have a simple class declared in a .h file and defined in .cpp file.  Both files are open in nvim at the same time.  I go to the header file, and change the name of the attribute and then save the file.  I flip over to the cpp buffer and expect to see any reference to that old attribute name to be marked as an error, but nothing happens.  Then, when I go into insert mode, make a insignificant change (like add a space or something), and escape into normal mode, the errors finally become marked.  Similar is true when I change the attribute back in the .h file and save.  The error markings do not go away until I make another change in the cpp file.  Here is a simple example I wrote for reproduction:

`// Test.h

class Test {
public:
	Test(int attr);
private:
	int myAttribute;
};`

`// Test.cpp
#include "Test.h"

Test::Test(int attr): myAttribute(attr) {}

int main() {
	return 0;
}`

`# makefile
CC:=clang++

app: Test.o

clean:
	rm -f *.o app
`

**Comment by puremourning** [comment]
Sorry, but please can you raise on the YouCompleteMe repo (and fill in the issue template there) ?
