### ISSUE TITLE
The ycmd server keeps giving bad hmac on request.

### ISSUE THREAD

**Issue by iogf** [ycm-core/ycmd#1306]
Hi. i'm developing a plugin https://github.com/vyapp/vy/blob/development/vyapp/plugins/ycmd/client.py

for https://github.com/vyapp/vy

I have taken the algorithm to calculate the request hmac from https://github.com/ycm-core/ycmd/blob/master/examples/example_client.py

The method hmac_req in the YcmdServer is responsible by calculating
the hmac to be sent in the http request header. However i keep getting this from
ycmd server:

2019-09-06 23:28:29,282 - INFO - Dropping request with bad HMAC

some idea what could it be wrong? I have checked multiple times the hmac_req method algorithm but i can't find any divergence from what it is done in the
example_client.py at ycmd repository.

**Comment by bstaletic** [comment]
[This line][vyapp] in your client doesn't calculate the same thing as [this line][ex] in the example client.

[vyapp]: https://github.com/vyapp/vy/blob/development/vyapp/plugins/ycmd/client.py#L116
[ex]: https://github.com/ycm-core/ycmd/blob/master/examples/example_client.py

**Comment by iogf** [comment]
Sorry, which is the line in the example client? i Clicked on the link but it points to the beginning of the file.

**Comment by bstaletic** [comment]
Sorry, that was my bad, I have misread your code. I can't see anything wrong with your algorithm either.

You could look into `ycmd/hmac_plugin.py` and maybe figure out what's happening there. There's a `RequestAunthenticated` which returns `False` before you get the "bad HMAC" message.

**Comment by puremourning** [comment]
You’re adding the content type header after calculating the HMAC.

**Comment by iogf** [comment]
Well, the content type header is meant to be in the http headers. I calculate the HMAC based only on the json that goes in the http request body. I'm not sure if i understood the issue puremourning.

**Comment by bstaletic** [comment]
I gave this another look. Without any changes to your code, I was able to get ycmd to cooperate with a simple test data:

```
>>> import foo
>>> import work.ycmd.ycmd.hmac_utils as hmac_utils
>>> method = b'GET'
>>> path = b'/completions'
>>> body = b'{"line_num": 2, "column_num": 2, "filepath": "/foo", "file_data": {"/foo": {"contents": "asd", "filetypes": "a"}}}'
>>> method_str = 'GET'
>>> path_str = '/completions'
>>> body_dict = {"line_num": 2, "column_num": 2, "filepath": "/foo", "file_data": {"/foo": {"contents": "asd", "filetypes": "a"}}}
>>> ycmd = foo.YcmdServer('work.ycmd.ycmd', 11111, './default_settings.json', None)
Set hmac: b'pH7T1N1Q4PqMTdhl5SUXIVqVP5GbDBmX9IJnM8AsboI='
>>> serving on http://localhost:11111

>>> f =ycmd.hmac_req(method_str, path_str, body_dict, ycmd.hmac_secret)
>>> y = hmac_utils.CreateRequestHmac(method, path, body, ycmd.hmac_secret)
>>>
>>> from base64 import b64encode, b64decode
>>> f = b64decode(f)
>>>
>>> f == y
True
```

In the above, `foo` is your `client.py` and `y` (the result of ycmd hmac calculation) and `f` (the result of `foo` hmac calculation) was exactly the same.

I didn't try non-ascii characters. Ycmd assumes UTF8 everywhere, so ISO-8859-1 might be a problem. I also wasn't running `vy`, so I didn't attempt to hit [this line](https://github.com/ycm-core/ycmd/blob/master/ycmd/hmac_plugin.py#L80), rather I went traight for [`CreateRequestHmac()`](https://github.com/ycm-core/ycmd/blob/master/ycmd/hmac_utils.py#L43) (though I don't see that as the problem).
