### ISSUE TITLE
Update go completer tools submodule to latest version

### ISSUE THREAD

**Issue by preslavmihaylov** [ycm-core/ycmd#1308]
Th go completer submodule is checked out at https://github.com/golang/tools/tree/cf84161cff3fdeddfd5ab5e686c1e2c17cb5db04. The last commit is from May, 2019.

Since then, there have been numerous changes to the tool, which fixed a lot of bugs. In my Go project, I had to manually update the submodule in my checked out ycmd repo in order to get proper auto completion.

**Comment by preslavmihaylov** [comment]
I see that there is already a pull request open for this 29 days ago. Could we rivive it pls?

https://github.com/ycm-core/ycmd/pull/1301

**Comment by bstaletic** [comment]
I was about to mention #1301. I'm fine with updating the PR to contain gopls changes from the past ~month.

Ultimately, what it is missing is a review.

**Comment by bstaletic** [comment]
#1301 got merged.
