### ISSUE TITLE
ClangCompleter: compilation database support doesn't allow Out-Of-Source builds

### ISSUE THREAD

**Issue by ulidtko** [ycm-core/ycmd#1309]
Hi!

Perhaps I'm missing something (please point out), but I've spent considerable time now trying to get YCM to pick up C and C++ compile flags somewhat-generically for build systems I most often work with:
 * CMake-based projects (leveraging the `compile_commands.json` support)
 * KBuild projects (linux kernel, busybox, openwrt...)
 * GNU Autotools projects *curses silently*

All of these support variations on out-of-source builds, whereby I `mkdir BUILD` or `mkdir BUILD-debug` and try to keep every build state artifact within there.

Unfortunately it seems, I can't put my "builddir detection" crapcode anywhere that YCM would use it. [The `LoadCompilationDatabase` method][•] is oblivious to separate build-directories. The ycm_extra_conf.py (both local and global) too, has no way to return that information to YCM.

Of course, I tried using `ycm_core.CompilationDatabase` and `.GetCompilationInfoForFile()` directly in the global ycm_extra_conf, to no success. I'm not sure if this is caused by #1035 or something else; I just get `ValueError: still no compile flags` and `Compilation database path: None` in `:YcmDebugInfo`. 

Please help. I fail to see if it's a good idea to propose an "API extension" to YCM (a `build_dir` key in ycm_extra_conf.Settings() returned dict?..), or if this is something that should've worked already. I am insistent however, on out-of-source builds and making YCM play nice with them.

[•]: /ycm-core/ycmd/blob/master/ycmd/completers/cpp/flags.py#L221

**Comment by puremourning** [comment]
Ycmd works fine with out of tree build if you tel it the correct flags.

**Comment by ulidtko** [comment]
> Ycmd works fine with out of tree build if you tel it the correct flags.

@puremourning could you please spell out which exactly?

**Comment by puremourning** [comment]
I guess in general use absolute paths.

**Comment by bstaletic** [comment]
First of all, extra confs can do absolutely anything. As for the compilation databases, no you can't put them anywhere you want, you have to put them in a file's parent directory (one of).

If you don't want to use extra conf files, make a symlink to the actual database. If you do want extra confs, take a look at `include_paths_relative_to_dir` optional key and yes, use absolute paths.

**Comment by ulidtko** [comment]
@puremourning 

> I guess in general use absolute paths.

... Which would imply that I can only use **one compdb ever**, stuck with it even if I open anything else in vim, is that right? Or am I misunderstanding your solid advice dear sir.

--------------

@bstaletic 
> First of all, extra confs can do absolutely anything.

Right, as long as that "absolutely anything" fits into what YCM API admits (or is a boring unrelated side-effect a-la launching rockets). I failed to locate any API docs for ycm_extra_conf files, and instead read how they're used in the source. Still hasn't found a way to write this:

```py
# "local" .ycm_extra_conf.py at git repo root

def MyGuessBuildSubdirWithCompilationDatabaseExtraSmartly(_):
    # NOTE even if I implement this properly, YCM still can't use it
    return "BUILD-debug"

def Settings(**kwargs):
    """ YCM's clang-completer entry point """
    build_subdir = MyGuessBuildSubdirWithCompilationDatabaseExtraSmartly(kwargs)
    compile_db = os.path.join(project_root, build_subdir, 'compile_commands.json')
    return {
        'flags': [...],
        'cache': True,
        'can_you_please_use_this_path_that_i_detected': compile_db,# <-- FIXME can't do
    }
```

I anticipate what you'll likely suggest here next: to duplicate YCM's code, going all the way of using `ycm_core.CompilationDatabase` class to load the db, and then look up the flags in it, then return it in the `{'flags': …}` dict. Two problems with this. First, this is just plain ugly. Smells poor engineering. Second: I tried that, it doesn't work! I merely get an empty database, despite the json file is full of stuff. Is that because of async loading of the DB?.. Is that becase I'm just doing it wrong?.. I don't know. I tried enough.

> As for the compilation databases, no you can't put them anywhere you want, you have to put them in a file's parent directory (one of).

That logic is too inflexible for me -- that's why I'm trying to override it. The very same CMake puts `compile_commands.json` under **the build directory** which in general isn't the same as the source directory, and never one of its parents.

**Comment by ulidtko** [comment]
> make a symlink to the actual database

I tried that too, years ago; it doesn't work, ergonomically speaking.

I expect my tools to work *just right* with no extra steps required. Every extra step I have to remember to kick it rolling:
 * distracts me from *the actual task* at hand
 * is one more source of error
 * manifests as one extra brick in the pile of cognitive load that I have to carry when doing software.

So, no. That might sound as a decent workaround to you, the developer -- but from a users' perspective, it doesn't really work.

**Comment by puremourning** [comment]
Ok so the tone of this discussion has changed a bit. I’m going to say if you want some help getting your setups working how you like, head to our gitter channel. However as we haven’t identified and actual bug or implementable feature request, I’m going to close this issue. 

For the record I use YCM on hundreds of projects and I have never done an on-tree build in 20 years.

**Comment by ulidtko** [comment]
I honestly don't want to appear obnoxious, guys. But an impression is forming, that you don't even try to read through any of what I wrote...

Can you please Ctrl+f FIXME on this page above; doesn't that identify as an implementable feature request?

**Comment by ulidtko** [comment]
Ok. I apologize of my communication of the problem, because I clearly failed at it.

The crux of the issue was this:

    ycm_core.CompilationDatabase('/tmp/test/BUILD/compile_commands.json') # DOES NOT WORK
    ycm_core.CompilationDatabase('/tmp/test/BUILD')                       # WORKS

I thank you for your responses, and hope for understanding.
