### ISSUE TITLE
Tern server isn't starting.

### ISSUE THREAD

**Issue by iogf** [ycm-core/ycmd#1313]
Hi. I have built ycmd from source following instructions.

cd ~/bin/
git clone git@github.com:ycm-core/ycmd.git ycmd-code
cd ycmd-code
git submodule update --init --recursive
pacman -S clang cmake gcc-c++ make python3-devel typescript python3-dev
python build.py --all

I'm actualling implementing a vy plugin for ycmd. 

https://github.com/vyapp/vy/blob/development/vyapp/plugins/ycmd/client.py

It is now working well for python files but fails with js, java and c-family lanng.
As the plugin is not ready yet, in order to test the plugin it is neessary
to access the ycmd-code folder(which was cloned) them run 

vy -v /path/to/file.

I have the tern executable in the ycmd-code folder but it doesnt get started for
some reason.

**Comment by bstaletic** [comment]
What's in the ycmd logs? For tern, you need `node` in your `$PATH` and `tern` in `ycmd/third_party/tern_runtime/node_modules/bin/`. Does function `ShouldEnableTernCompleter()` from `ycmd/completers/javascript/tern_completer.py` return `True`?

> I'm actualling implementing a vy plugin for ycmd.

When you think the plugin is usable, make a PR to list your plugin in the list of clients.

**Comment by iogf** [comment]
ShouldEnableTern returns True yes.

The logs for ycmd are:

~~~
[tau@archlinux ycmd-code]$ vy -v ~/oo.js 
2019-09-15 13:02:25,239 - DEBUG - No global extra conf, not calling method YcmCorePreload
serving on http://localhost:43247
2019-09-15 13:02:28,123 - INFO - Received completion request
2019-09-15 13:02:28,131 - INFO - Using node binary from: /usr/bin/node
2019-09-15 13:02:28,132 - DEBUG - Using filetype completion: True
2019-09-15 13:02:28,133 - ERROR - Exception from semantic completer (using general)
Traceback (most recent call last):
  File "/home/tau/bin/ycmd-code/ycmd/handlers.py", line 100, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/tau/bin/ycmd-code/ycmd/completers/completer.py", line 235, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/tau/bin/ycmd-code/ycmd/completers/completer.py", line 248, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/tau/bin/ycmd-code/ycmd/completers/javascript/tern_completer.py", line 182, in ComputeCandidatesInner
    request_data )
  File "/home/tau/bin/ycmd-code/ycmd/completers/javascript/tern_completer.py", line 367, in _GetResponse
    return self._PostRequest( { 'query': full_query }, request_data )
  File "/home/tau/bin/ycmd-code/ycmd/completers/javascript/tern_completer.py", line 313, in _PostRequest
    raise ValueError( 'Not connected to server' )
ValueError: Not connected to server
2019-09-15 13:02:30,735 - DEBUG - Shutting down Tern server
2019-09-15 13:02:30,735 - DEBUG - No global extra conf, not calling method VimClose
2019-09-15 13:02:30,735 - DEBUG - No global extra conf, not calling method Shutdown
[tau@archlinux ycmd-code]$ 

~~~

Can you try running vy and open a js file there? You just need to move the cursor to the line then hit Control-period in INSERT mode. 

First you'll need to enable ycmd in your vyrc file.
Open ~/.vy/vyrc then uncomment this line.

~~~python
# Auto completion using ycmd.
# from vyapp.plugins.ycmd import client
# client.YcmdCompletion.setup('ycmd')
# autoload(client)
~~~

Also comment the standard python completer jedi.

~~~

import vyapp.plugins.jedi
autoload(vyapp.plugins.jedi)
~~~

Comment the above lines then you'll be ready to test ycmd in vy.

Here are the steps:

# It is necessary to cd into the ycmd because ycmd plugin isnt ready. It is just for testing purposes.

cd ycmd-code
vy -v /path/to/jsfile
~~~

Then move to the line/col, you will be in NORMAL mode you can use
basic vim key strokes to move the cursor around like hjkl.

Once on the line/col just press <Key-i> it will get you in INSERT mode then hit <Control-period>

**Comment by bstaletic** [comment]
I tried to test with vy, but I got

    ModuleNotFoundError: No module named 'vyapp.plugins.ycmd'

and the ycmd related config lines didn't exist at all. I cloned the latest master.

Try ycmd with some other client. If it works, the problem is within your plugin. If it doesn't either there's an error in your setup or ycmd has a bug. We've basically moved to using TSServer for javascript as well and that's what we test. Support for tern is only there because some javascript projects don't work with TSServer.

**Comment by iogf** [comment]
Did you install the development branch?

**Comment by iogf** [comment]
I tried it with vim but no success at all.

**Comment by bstaletic** [comment]
> Did you install the development branch?

No, but this is what I got after cloning the development branch:

```
2019-09-15 18:51:01,723 - INFO - Dropping request with bad HMAC
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/bstaletic/work/vy/vyapp/plugins/ycmd/client.py", line 148, in <lambda>
    completions = lambda event: YcmdWindow(event.widget, self.server)
  File "/home/bstaletic/work/vy/vyapp/plugins/ycmd/client.py", line 141, in __init__
    area.filename, data, dirname(area.filename))
  File "/home/bstaletic/work/vy/vyapp/plugins/ycmd/client.py", line 95, in completions
    return self.fmt_options(req.json())
  File "/home/bstaletic/work/vy/vyapp/plugins/ycmd/client.py", line 99, in fmt_options
    'Type:%s' % ind['kind']) for ind in data['completions']]
KeyError: 'completions'
serving on http://localhost:43247
```

> I tried it with vim but no success at all.

You'll have to be more specific. What exactly didn't work? Because I tried tern with YouCompleteMe and it, expectedly, complained about missing a tern configuration file.

**Comment by iogf** [comment]
That is quite weird. It doesn't complain about bad hmac here. There was a bug with the code that was giving that error however i fixed it. 

Are you sure you running the same development branch version that i'm now?

https://github.com/vyapp/vy/blob/development/vyapp/plugins/ycmd/client.py

Can you post your ycmd.client code here? so i can check if it matches what it is expected.

When i run vy -v ~/oo.js and i try to get completions it raises exception telling the tern server is not running. It seems ycmd isn't starting tern server at all. When i run ycmd manually it doesn't start tern server either.

**Comment by bstaletic** [comment]
Okay, here's a few things I've noticed:

- Opening `oo.js` when it doesn't exist in the filesystem crashes `vy`.
- Opening `ycmd/tests/javascript/testdata/test.js` resulted in "invalid hmac".
- Opening an empty javascript file produced the following traceback:

```
2019-09-15 19:41:12,190 - INFO - Received completion request
2019-09-15 19:41:12,192 - INFO - Using node binary from: /usr/sbin/node
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/bstaletic/work/vy/vyapp/widgets.py", line 44, in dispatch
    if event.char:  self.on_char(event.char)
  File "/home/bstaletic/work/vy/vyapp/completion.py", line 70, in on_char
    self.index, 'insert'))
  File "/home/bstaletic/work/vy/vyapp/widgets.py", line 28, in selection_item
    index = self.startswith(data)
  File "/home/bstaletic/work/vy/vyapp/widgets.py", line 21, in startswith
    raise ValueError
ValueError
```

> Are you sure you running the same development branch version that i'm now?

Yes, I even did a diff between the linked file and the one I have locally.

**Comment by iogf** [comment]
Try to open an oo.js when it is with:

~~~javascript
var fs = require(fs);
fs.
~~~

Try to complete fs.
It is expected by vy to raise an exception when the file doesn't exist in the system.

**Comment by iogf** [comment]
Which version of ycmd are you using? is it python3 or python2?

**Comment by iogf** [comment]
I mean are you using ycmd with python3 or 2?

**Comment by bstaletic** [comment]
With that file content I did encounter the traceback that you did, but vim/YouCompleteMe/ycmd works fine.

Though with YCM I do get a warning that I don't have a `.tern-config.js`. Is `vy` capable of handling warnings/errors from ycmd that are send as an [`ExceptionResponse`](https://ycm-core.github.io/ycmd/#/definitions/ExceptionResponse).

**Comment by iogf** [comment]
I have placed a .tern-config file in ~/ however even so in vy it fails. It says there is no tern server running. The auto completion works fine for python etc but not for tern.

What you mean with handling warnings/errors? Vy ycmd plugin is in a really early stage despite of being relatively functional. It remains some tweakings before it being ready for being used.

How did you install vim youcompleteme? I installed it from aur but it didnt work at all.
You can try finding your youcompleteme files then cd /path/to/youcompleteme/ycmd

then vy -v ~/oo.js

it should work too. Maybe it works there since it is working for vim.

**Comment by bstaletic** [comment]
> What you mean with handling warnings/errors? Vy ycmd plugin is in a really early stage despite of being relatively functional. It remains some tweakings before it being ready for being used.

Does the linked `ExceptionResponse` cause a connection to ycmd to die?

> How did you install vim youcompleteme?

I'm a maintainer, so it's much easier for me to clone YCM directly in `~/.vim/whatever/YouCompleteMe`. I've never tried the AUR package.

> You can try finding your youcompleteme files then cd /path/to/youcompleteme/ycmd then vy -v ~/oo.js It should work too. Maybe it works there since it is working for vim.

That's exactly what I did above. Tern works with YCM, doesn't work with vy.

**Comment by iogf** [comment]
No, the exception doesn't kill ycmd at all. You can do this:

vy -v ~/oo.js ~/dd.py

You can try completing in both files. Even after the completion in oo.js failing it still works with dd.py.

The thing is that tern doesn't start when ycmd starts.

**Comment by bstaletic** [comment]
> The thing is that tern doesn't start when ycmd starts.

That's it! [`_StartServer()` for tern (and some other servers) is executed only once the client sends `FileReadyToParse` event](https://github.com/ycm-core/ycmd/blob/master/ycmd/completers/javascript/tern_completer.py#L223).

**Comment by iogf** [comment]
Good one. I'll do that. Thank you man.

**Comment by iogf** [comment]
It seem to work now. I'll now get it to work for c-family. Thank you again.
