### ISSUE TITLE
No clangd executable found.

### ISSUE THREAD

**Issue by iogf** [ycm-core/ycmd#1325]
Hi. I'm developing a ycmd plugin for vy https://github.com/vyapp/vy/tree/development/vyapp/plugins/ycmd

I have compiled ycmd with 
~~~
cd ~/bin/
git clone git@github.com:ycm-core/ycmd.git ycmd-code
cd ycmd-code
ls
git submodule update --init --recursive
ls

# typescript is for tsserver. clang is for c-family completion.
pacman -S clang cmake gcc-c++ make python3-devel typescript python3-dev

# Compiling ycmd with all features. The --cs-completer, -go-completer are 
# flags to install the necessary tools.
python3 install.py --all --cs-completer -go-completer --rust-completer --java-completer --clang-completer

~~~

The .ycm_extra_conf.py file that i'm using is the default one https://github.com/vyapp/vy/blob/development/vyapp/plugins/ycmd/ycm_extra_conf.py

I'm on arch linux.

~~~
[tau@archlinux ~]$ vy foo.c 
serving on http://localhost:4736
2019-09-21 09:14:34,018 - INFO - Received event notification
2019-09-21 09:14:34,019 - INFO - Adding buffer identifiers for file: /home/tau/foo.c
2019-09-21 09:14:34,064 - INFO - No Clangd executable found in /home/tau/bin/ycmd-code/third_party/clangd/output/bin
Traceback (most recent call last):
  File "/home/tau/bin/ycmd-code/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/tau/bin/ycmd-code/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/tau/bin/ycmd-code/ycmd/watchdog_plugin.py", line 104, in wrapper
    return callback( *args, **kwargs )
  File "/home/tau/bin/ycmd-code/ycmd/hmac_plugin.py", line 68, in wrapper
    body = callback( *args, **kwargs )
  File "/home/tau/bin/ycmd-code/ycmd/handlers.py", line 67, in EventNotification
    event_handler )( request_data )
  File "/home/tau/bin/ycmd-code/ycmd/completers/cpp/clang_completer.py", line 380, in OnFileReadyToParse
    flags, filename = self._FlagsForRequest( request_data )
  File "/home/tau/bin/ycmd-code/ycmd/completers/cpp/clang_completer.py", line 479, in _FlagsForRequest
    return self._flags.FlagsForFile( filename, client_data = client_data )
  File "/home/tau/bin/ycmd-code/ycmd/completers/cpp/flags.py", line 139, in FlagsForFile
    results = self._GetFlagsFromExtraConfOrDatabase( filename, client_data )
  File "/home/tau/bin/ycmd-code/ycmd/completers/cpp/flags.py", line 174, in _GetFlagsFromExtraConfOrDatabase
    module = extra_conf_store.ModuleForSourceFile( filename )
  File "/home/tau/bin/ycmd-code/ycmd/extra_conf_store.py", line 62, in ModuleForSourceFile
    return Load( ModuleFileForSourceFile( filename ) )
  File "/home/tau/bin/ycmd-code/ycmd/extra_conf_store.py", line 73, in ModuleFileForSourceFile
    if Load( module_file ):
  File "/home/tau/bin/ycmd-code/ycmd/extra_conf_store.py", line 158, in Load
    if not force and not _ShouldLoad( module_file, is_global ):
  File "/home/tau/bin/ycmd-code/ycmd/extra_conf_store.py", line 141, in _ShouldLoad
    raise UnknownExtraConf( module_file )
ycmd.responses.UnknownExtraConf: Found /home/tau/.ycm_extra_conf.py. Load? 

(Question can be turned off with options, see YCM docs)
~~~

No idea why it is not working. I'm giving the path to .ycm_extra_conf.py with the filereadytoparse event. I wonder if it is really necessary in a general case. Would ycmd load a .ycm_extra_conf.py file if it is in the working directory of the project regardless of specifying the extra conf file in the filereadytoparse event or somewhere else?

**Comment by bstaletic** [comment]
>     python3 install.py --all --cs-completer -go-completer --rust-completer --java-completer --clang-completer

`--all` makes all those other flags redundant.

> No clangd executable found

This is expected when using the older libclang based completer.

https://github.com/ycm-core/ycmd/blob/master/ycmd/completers/cpp/hook.py

Ycmd first checks if it should enable the clangd based completer.

> Extra conf file

That file is used for more than just C. A user can configure the jdt.ls server with it for example. Python users can use it to configure their python path and jedi interpreter. I believe even C# has a use for extra conf files. As far as C family goes, the extra conf is used to supply compiler flags to ycmd, with the alternative of having `compile_commands.json` fill this purpose.

In order of priority, ycmd will look for these:

1. local extra conf
2. compilation database
3. global extra conf

When a user opens a new file, ycmd scans all parent directories until it finds one of the above. If it happens to find an extra conf that is:

- not in the blacklist
- not in the whitelist
- not a global extra conf

ycmd will raise an `UnknownExtraConf` exception. The client is supposed to catch the exception and ask the user if that extra conf should be loaded. The blacklist, whitelist and prompt are there to protect user from arbitrary code execution.

So `FileReadyToParse` doesn't come into play at all for this.

**Comment by iogf** [comment]
Is it really necessary to ask the user if he wants to load the given .ycm conf file? It seems a bit redundant somehow. Is there really an imminent risky of it being automatic in the context of ycmd? 

Also it seem to work for c++ right now but still fails for c. When using that default .ycm_extra_conf.py file.

**Comment by iogf** [comment]
Also when using the pure jedi package it gives docs for the functions, classes etc. In ycmd it doesn't give the documentation for the objects. Is there some parameter that has to be given?

**Comment by puremourning** [comment]
The confirmation is necessary as extra conf files can run arbitrary code. Much like HMAC they are required to ensure then security for users. This is not optional.

**Comment by puremourning** [comment]
> Also when using the pure jedi package it gives docs for the functions, classes etc. In ycmd it doesn't give the documentation for the objects.

Please use one issue for one isssue/question. Need logs, exact use case etc.
