### ISSUE TITLE
Ycmd doesn't give diagnostics for python files.

### ISSUE THREAD

**Issue by iogf** [ycm-core/ycmd#1326]
Am i mistaken or ycmd doesn't provide diagnostics for python files when FileReadyToParse event is sent? It works fine for c++ and c but not for python nor javascript it seems.

**Comment by bstaletic** [comment]
As you can see in [this list](https://github.com/ycm-core/YouCompleteMe/#python), there's no support for "Real-time diagnostic display".

**Comment by bstaletic** [comment]
Javascript has diagnostics if you use typescript completer for javascript as well.
