### ISSUE TITLE
Bad HMAC when it is HTTP GET for /healthy handle.

### ISSUE THREAD

**Issue by iogf** [ycm-core/ycmd#1328]
Hi. 

The questions below are related to https://github.com/vyapp/vy/blob/development/vyapp/plugins/ycmd/client.py

The method YcmdServer.is_alive sends a '/healthy' to ycmd instance. The YcmdServer.post method works seamlessly but YcmdServer.get is failing it causes a 'Dropping request with bad HMAC'. 

I'm wondering why YcmdServer.hmac_req method works correctly to calculate the HMAC for HTTP POST requests but fails for HTTP GET requests.

I calculate the HMAC for HTTP GET requests with       

~~~python
hmac_secret = self.hmac_req('GET', 
        'path', '', self.hmac_secret)
~~~

Where the '' means an empty body.

~~~python
        hmac_secret = self.hmac_req('GET', 
        '/healthy', '', self.hmac_secret)
~~~

Considerying the healthy HTTP route the above code does the calculation for the HMAC but it fails miserably it seems.

Some idea what could it be wrong?

**Comment by bstaletic** [comment]
Passing `b''` [here](https://github.com/vyapp/vy/blob/development/vyapp/plugins/ycmd/client.py#L217) returns `b'""'`, which is not `b''` and results in a different HMAC. At least I think that's the problem, I haven't tested your client, just gave it a good look.

**Comment by puremourning** [comment]
Agree with Boris that seems likely to be culprit. Maybe use None to mean no body?

**Comment by puremourning** [comment]
Doesn’t seem likely this is a ycmd issue, so closing.
