### ISSUE TITLE
PR #1275 broke GoTo for member functions

### ISSUE THREAD

**Issue by bstaletic** [ycm-core/ycmd#1341]
Just like the title says. I tried reverting the PR locally and it made `GoTo` work again.

**Comment by bstaletic** [comment]
What's even weirder, right now, `GoToType` works for member functions...

**Comment by puremourning** [comment]
Example? GoTo works for me in python ...

**Comment by bstaletic** [comment]
Try `:YcmCompleter GoTo` on [`PostDataToHandler` in signature_help_request.py results in a traceback](https://github.com/puremourning/YouCompleteMe/blob/signature-help/python/ycm/client/signature_help_request.py#L40). You tested this one in gitter.

The same `:YcmCompleter GoTo` on [this line](https://github.com/puremourning/YouCompleteMe/blob/signature-help/python/ycm/client/command_request.py#L56) doesn't result in a traceback, but ends up in a wrong file\*.

Right now, jumping to a member function never seems to take us to a different file.

**Comment by bstaletic** [comment]
So here's what happens:

- We are using `goto_assignments()` for `GoTo`.
- We are not using `follow_imports` because we want to stop on any alias import statement.
- In order to get to another file with a `goto_statements()` call, there has to be an `import` line.
- There are no import lines for member access.
  - This is true for any member, data or function.
  - **This is where our assumption is broken.**
- So what ends up happening is that `goto_assignments()` on a member returns:
  - Line from the definition
  - Column from the definition
  - Filepath from the point of use
  - **This is where jedi return value makes no sense**
  - We try to use a "malformed" location in an attempt to get to the include line and one of these two outcomes happens:
    - If definition line number is within range [0, len(point_of_use_lines) we end up jumping to that "malformed" location.
    - Else jedi throws an exception

Unlike `GoTo` (`goto_assignments()`), `GoToType` (`goto_definitions()`) immediately returns:
  - Line of definition
  - Column of definition
  - Filepath of definition

**Comment by bstaletic** [comment]
As I mentioned in ycm-core/YouCompleteMe#3458, this can also end up causing an infinite loop.

To see this happen, open `signature_help_request.py` and run `:YcmCompleter GoTo` on `_response_future` on [this line](https://github.com/puremourning/YouCompleteMe/blob/master/python/ycm/client/signature_help_request.py#L49).
