### ISSUE TITLE
LSP: Check Server Capabilities before sending request

### ISSUE THREAD

**Issue by slrtbtfs** [ycm-core/ycmd#1347]
The ycmd server currently  sends some requests to LSP language server evens if they didn't advertise the necessary capabilities, e.g. `DidChangeConfiguration` or `Completion`.

It would be nice if the ycmd would be more LSP compliant here.

**Comment by bstaletic** [comment]
Is there an actual problem you are facing?

For `completion` request, we do assume the server does support it, because, frankly, what good is a server that doesn't do completions? `didChangeConfiguration` behaviour, I think is the same as in vscode.

**Comment by slrtbtfs** [comment]
Yes, because I'm currently developing a language server (<https://github.com/slrtbtfs/promql-lsp>) which doesn't have completion _yet_. However it already has support for diagnostics and hover request, which I'd like to test with as many language clients as possible.

It is possible to work around this issue by just sending an empty reply in these cases, but this technically makes the server non compliant, because the correct answer would be an error message.

Vscode only sends `didChangeConfiguration` requests if the server advertises workspace capabilities.

**Comment by bstaletic** [comment]
Here's a patch that *should* make ycmd behave with your server.

```diff
diff --git a/ycmd/completers/language_server/language_server_completer.py b/ycmd/completers/language_server/language_server_completer.py
index fe103912..3fb5ad19 100644
--- a/ycmd/completers/language_server/language_server_completer.py
+++ b/ycmd/completers/language_server/language_server_completer.py
@@ -1603,6 +1603,9 @@ class LanguageServerCompleter( Completer ):
       self._server_capabilities = response[ 'result' ][ 'capabilities' ]
       self._resolve_completion_items = self._ShouldResolveCompletionItems()

+      if 'completionProvider' not in self._server_capabilities:
+        self.ComputeCandidatesInner = lambda a, b, c: None, False
+
       if 'textDocumentSync' in self._server_capabilities:
         sync = self._server_capabilities[ 'textDocumentSync' ]
         SYNC_TYPE = [
@@ -1657,8 +1660,9 @@ class LanguageServerCompleter( Completer ):
       # https://github.com/Microsoft/language-server-protocol/issues/567 the
       # configuration should be send in response to a workspace/configuration
       # request?
-      self.GetConnection().SendNotification(
-          lsp.DidChangeConfiguration( self._settings ) )
+      if 'workspace' in self._server_capabilities:
+        self.GetConnection().SendNotification(
+            lsp.DidChangeConfiguration( self._settings ) )

       # Notify the other threads that we have completed the initialize exchange.
       self._initialize_response = None
```

Full disclojure: I haven't tested the patch and given that I don't have a server that doesn't support completions, I couldn't test it. Try it and tell us if the patch worked.

**Comment by puremourning** [comment]
Hmmm. A server that doesn't offer completions is not something that we have considered with ycmd. 

I suppose we could check `completionProvider` in `ShouldUseNowInner`.

I don't see anything in the spec that says `didChangeConfiguration` is dependent on a server capability.

**Comment by puremourning** [comment]
Heh, overlap, I think I prefer this patch"

```
diff --git a/ycmd/completers/language_server/language_server_completer.py b/ycmd/completers/language_server/language_server_completer.py
index 0b76dd09..6042036e 100644
--- a/ycmd/completers/language_server/language_server_completer.py
+++ b/ycmd/completers/language_server/language_server_completer.py
@@ -873,6 +873,7 @@ class LanguageServerCompleter( Completer ):
   def ShouldUseNowInner( self, request_data ):
     # We should only do _anything_ after the initialize exchange has completed.
     return ( self._ServerIsInitialized() and
+             'completion' in self._server_capabilities and
              super( LanguageServerCompleter, self ).ShouldUseNowInner(
                request_data ) )
```

**Comment by bstaletic** [comment]
Your patch is doing `'completionProvider' in self._server_capabilities` on every request. My patch avoids that overhead and I believe that is important for such a common request.

**Comment by puremourning** [comment]
Yeah but we're still doing the regex check on every `ShouldUseNow` call :). My patch could be bmade better by storing the result of the check when we finish the init exchange, I admit.

I'm not a fan of rewriting code at runtime (it's hard to debug), but you could at least patch out `SHouldUseNow` rather than `ComputeCandidates` ?

**Comment by bstaletic** [comment]
If we are going to patch things, `ComputeCandidates` (not `Inner`) is furthest up the stack, though that is of no importance, I believe. In the end, I don't care what exactly we patch out. You're also right about debuggability, but I thought this was simple enough to be acceptable.

**Comment by slrtbtfs** [comment]
Thanks for the quick replys!

@puremourning I've tested your patch. It works.

**Comment by bstaletic** [comment]
#1348 got merged.
