### ISSUE TITLE
Plan to drop python 2 support

### ISSUE THREAD

**Issue by bstaletic** [ycm-core/ycmd#1365]
Same story as  ycm-core/YouCompleteMe#3538

- [ ] Drop `python-future` dependency.
- [ ] Remove python 2 from `build.py` and `CMakeLists.txt`.
- [ ] Remove all `PY2` conditional code and `__future__` imports.
- [ ] Replace `super( Class, self )` with `super()`.
- [ ] Remove `# coding: utf-8` headers from files.
- [ ] Use `class C:` instead of `class C( object ):`.
- [ ] Use `str.encode()` instead of `str.encode( 'utf-8' )`.
- [ ] Replace the single use of `inspect.getargspec().keywords` with `inspect.getfullargspec().varkw`

Did I miss anything?

**Comment by hugovk** [comment]
https://github.com/asottile/pyupgrade can help automatically upgrading some things.

Run it like this:
```sh
pip install -U pyupgrade
pyupgrade `find . -name "*.py" -type f` --py3-plus
```

**Comment by bstaletic** [comment]
Thanks for the pointer. I have already done things manually in a local branch. 
https://github.com/bstaletic/ycmd/tree/no_py2
