### ISSUE TITLE
CSharp Completer - "Type" response field is sometimes empty

### ISSUE THREAD

**Issue by resolritter** [ycm-core/ycmd#1385]
https://github.com/ycm-core/ycmd/blob/5091b462e7e03759e6aa8c6eb3b8ed05df50e4a8/ycmd/completers/cs/cs_completer.py#L701

I've logged the request's response and found out that, sometimes, the [ "Type" ] field comes out as `None`. _Sometimes_ means it works reliably for some cases, but not for all of them.

When it's missing, it causes YCM to thrown an exception, although it does not seem like the fault of it being absent is in our end - this is simply a unexpected failure case not being handled.

---

I can reproduce the empty response 100% of the time in the following situations
- When trying to get the documentation for a generic Class
- When trying to get the documentation for a [Field](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/fields) in an Interface

Those are situations to be reported in-depth in [omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn) perhaps, but I think YCM needs to handle the case where the response comes as `None` and not have it blow up inadvertently. It's happening very often in a fairly robust project.

**Comment by bstaletic** [comment]
That's for the report. This can be fixed pretty easily, but we'll need a repro case in order to write tests.

**Comment by resolritter** [comment]
@bstaletic 
> we'll need a repro case in order to write tests.

I can reproduce it reliably in the following file (**_note:_** the project isn't mine, it's just something I found by chance)

https://github.com/Capnode/Algoloop/blob/3b96ededf1fdebd29985defc49bc5af24e8a0e0b/Indicators/WindowIdentity.cs#L22

If you try to `YcmCompleter GetDoc` with the cursor over at WindowIndicator, for instance, you'll verify the first case.

And for verifying the second case, you can repeat the action with the cursor at `Samples`.

This is of course not limited to `GetDoc`, but other commands which rely on type lookup as well.

**Comment by resolritter** [comment]
FWIW I've tried upgrading to the latest release of omnisharp-roslyn (1.34.9), but it seems like this isn't solved still

**Comment by bstaletic** [comment]
https://gist.github.com/bstaletic/775525013fa94274a0f8722a31d82a34

That patch should solve the issue. Try it out.
