### ISSUE TITLE
unable to build on Mac OSX Catalina

### ISSUE THREAD

**Issue by bananaspliff** [ycm-core/ycmd#1390]
branch master and clang

➜  ~ git clone https://github.com/Valloric/ycmd.git ~/.ycmd
Cloning into '/Users/xavier/.ycmd'...
remote: Enumerating objects: 26867, done.
remote: Total 26867 (delta 0), reused 0 (delta 0), pack-reused 26867
Receiving objects: 100% (26867/26867), 19.90 MiB | 2.98 MiB/s, done.
Resolving deltas: 100% (17347/17347), done.
➜  ~ cd ~/.ycmd
➜  .ycmd git:(master) git submodule update --init --recursive
Submodule 'third_party/bottle' (https://github.com/defnull/bottle) registered for path 'third_party/bottle'
Submodule 'third_party/cregex' (https://github.com/ycm-core/regex.git) registered for path 'third_party/cregex'
Submodule 'third_party/go/src/golang.org/x/tools' (https://github.com/golang/tools) registered for path 'third_party/go/src/golang.org/x/tools'
Submodule 'third_party/jedi' (https://github.com/davidhalter/jedi) registered for path 'third_party/jedi_deps/jedi'
Submodule 'third_party/jedi_deps/numpydoc' (https://github.com/numpy/numpydoc) registered for path 'third_party/jedi_deps/numpydoc'
Submodule 'third_party/parso' (https://github.com/davidhalter/parso) registered for path 'third_party/jedi_deps/parso'
Submodule 'third_party/certifi' (https://github.com/certifi/python-certifi) registered for path 'third_party/requests_deps/certifi'
Submodule 'third_party/chardet' (https://github.com/chardet/chardet) registered for path 'third_party/requests_deps/chardet'
Submodule 'third_party/idna' (https://github.com/kjd/idna) registered for path 'third_party/requests_deps/idna'
Submodule 'third_party/requests' (https://github.com/requests/requests) registered for path 'third_party/requests_deps/requests'
Submodule 'third_party/urllib3' (https://github.com/urllib3/urllib3) registered for path 'third_party/requests_deps/urllib3'
Submodule 'third_party/waitress' (https://github.com/Pylons/waitress) registered for path 'third_party/waitress'
Cloning into '/Users/xavier/.ycmd/third_party/bottle'...
Cloning into '/Users/xavier/.ycmd/third_party/cregex'...
Cloning into '/Users/xavier/.ycmd/third_party/go/src/golang.org/x/tools'...
Cloning into '/Users/xavier/.ycmd/third_party/jedi_deps/jedi'...
Cloning into '/Users/xavier/.ycmd/third_party/jedi_deps/numpydoc'...
Cloning into '/Users/xavier/.ycmd/third_party/jedi_deps/parso'...
Cloning into '/Users/xavier/.ycmd/third_party/requests_deps/certifi'...
Cloning into '/Users/xavier/.ycmd/third_party/requests_deps/chardet'...
Cloning into '/Users/xavier/.ycmd/third_party/requests_deps/idna'...
Cloning into '/Users/xavier/.ycmd/third_party/requests_deps/requests'...
Cloning into '/Users/xavier/.ycmd/third_party/requests_deps/urllib3'...
Cloning into '/Users/xavier/.ycmd/third_party/waitress'...
Submodule path 'third_party/bottle': checked out '7423aa0f64e381507d1e06a6bcab48888baf9a7b'
Submodule path 'third_party/cregex': checked out 'cc538bb6d0fcf0a6411537a5522d13cc9b86789d'
Submodule path 'third_party/go/src/golang.org/x/tools': checked out '58d531046acdc757f177387bc1725bfa79895d69'
Submodule path 'third_party/jedi_deps/jedi': checked out '35e5cf2c2aa7c2f2c8ea08d74ef64f681582e49e'
Submodule 'jedi/third_party/typeshed' (https://github.com/davidhalter/typeshed.git) registered for path 'third_party/jedi_deps/jedi/jedi/third_party/typeshed'
Cloning into '/Users/xavier/.ycmd/third_party/jedi_deps/jedi/jedi/third_party/typeshed'...
Submodule path 'third_party/jedi_deps/jedi/jedi/third_party/typeshed': checked out '3319cadf85012328f8a12b15da4eecc8de0cf305'
Submodule path 'third_party/jedi_deps/numpydoc': checked out 'c8513c5db6088a305711851519f944b33f7e1b25'
Submodule 'doc/scipy-sphinx-theme' (https://github.com/scipy/scipy-sphinx-theme) registered for path 'third_party/jedi_deps/numpydoc/doc/scipy-sphinx-theme'
Cloning into '/Users/xavier/.ycmd/third_party/jedi_deps/numpydoc/doc/scipy-sphinx-theme'...
Submodule path 'third_party/jedi_deps/numpydoc/doc/scipy-sphinx-theme': checked out 'bc3b4b8383d4cd676fe75b7ca8c3e11d6afa8d97'
Submodule path 'third_party/jedi_deps/parso': checked out '59df3fab4358d5889556c2450c2d1deb36facdb7'
Submodule path 'third_party/requests_deps/certifi': checked out '5b9e05c06e69fe5c7835052cfc3ae1c899dfc8b1'
Submodule path 'third_party/requests_deps/chardet': checked out '9b8c5c2fb118d76c6beeab9affd01c332732a530'
Submodule path 'third_party/requests_deps/idna': checked out '0f50bdcea71e6602bf4cd22897970d71fc4074d9'
Submodule path 'third_party/requests_deps/requests': checked out '6cfbe1aedd56f8c2f9ff8b968efe65b22669795b'
Submodule path 'third_party/requests_deps/urllib3': checked out 'a6ec68a5c5c5743c59fe5c62c635c929586c429b'
Submodule path 'third_party/waitress': checked out '7bb27bb66322fc564e14005d29cb6fddd76a0ab6'
➜  .ycmd git:(master) ./build.py --clang-completer --system-libclang
Searching Python 3.7 libraries...
Found Python library: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/libpython3.7.dylib
Found Python headers folder: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/Headers
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonLibs: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/libpython3.7.dylib (found suitable version "3.7.3", minimum required is "3.5")
-- Using libclang to provide semantic completion for C/C++/ObjC
-- Using external libclang: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib
-- NOT using clang-tidy for static analysis.
-- Configuring done
-- Generating done
-- Build files have been written to: /private/var/folders/rh/dn44qkfx70l59tkkc76vzb2h0000gt/T/ycm_build_pfavokam
Scanning dependencies of target BoostParts
[  1%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/filesystem/src/codecvt_error_category.cpp.o
[  3%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/filesystem/src/operations.cpp.o
[  5%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/filesystem/src/path.cpp.o
[  7%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/filesystem/src/path_traits.cpp.o
[  9%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/filesystem/src/portability.cpp.o
[ 13%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/filesystem/src/utf8_codecvt_facet.cpp.o
[ 13%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/filesystem/src/unique_path.cpp.o
[ 15%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/filesystem/src/windows_file_codecvt.cpp.o
[ 17%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/regex/src/c_regex_traits.cpp.o
[ 19%] Building CXX object BoostParts/CMakeFiles/BoostParts.dir/libs/regex/src/cpp_regex_traits.cpp.o
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2082:32: error: out-of-line definition of 'm_get_status' does not match any declaration in 'boost::filesystem::directory_entry'; did you
      mean 'get_status'?
  file_status directory_entry::m_get_status(system::error_code* ec) const
                               ^~~~~~~~~~~~
                               get_status
/usr/local/include/boost/filesystem/directory.hpp:145:37: note: 'get_status' declared here
  BOOST_FILESYSTEM_DECL file_status get_status(system::error_code* ec=0) const;
                                    ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2102:32: error: out-of-line definition of 'm_get_symlink_status' does not match any declaration in 'boost::filesystem::directory_entry';
      did you mean 'get_symlink_status'?
  file_status directory_entry::m_get_symlink_status(system::error_code* ec) const
                               ^~~~~~~~~~~~~~~~~~~~
                               get_symlink_status
/usr/local/include/boost/filesystem/directory.hpp:146:37: note: 'get_symlink_status' declared here
  BOOST_FILESYSTEM_DECL file_status get_symlink_status(system::error_code* ec=0) const;
                                    ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2387:22: error: 'dir_itr_close' is missing exception specification 'noexcept'
  system::error_code dir_itr_close( // never throws
                     ^
/usr/local/include/boost/filesystem/directory.hpp:204:20: note: previous declaration is here
system::error_code dir_itr_close(// never throws()
                   ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2427:44: error: 'm_imp' is a private member of 'boost::filesystem::directory_iterator'
      error_code result = dir_itr_first(it.m_imp->handle,
                                           ^
/usr/local/include/boost/filesystem/directory.hpp:333:47: note: declared private here
  boost::intrusive_ptr< detail::dir_itr_imp > m_imp;
                                              ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2429:12: error: 'm_imp' is a private member of 'boost::filesystem::directory_iterator'
        it.m_imp->buffer,
           ^
/usr/local/include/boost/filesystem/directory.hpp:333:47: note: declared private here
  boost::intrusive_ptr< detail::dir_itr_imp > m_imp;
                                              ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2435:12: error: 'm_imp' is a private member of 'boost::filesystem::directory_iterator'
        it.m_imp.reset();
           ^
/usr/local/include/boost/filesystem/directory.hpp:333:47: note: declared private here
  boost::intrusive_ptr< detail::dir_itr_imp > m_imp;
                                              ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2441:14: error: 'm_imp' is a private member of 'boost::filesystem::directory_iterator'
      if (it.m_imp->handle == 0)
             ^
/usr/local/include/boost/filesystem/directory.hpp:333:47: note: declared private here
  boost::intrusive_ptr< detail::dir_itr_imp > m_imp;
                                              ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2442:12: error: 'm_imp' is a private member of 'boost::filesystem::directory_iterator'
        it.m_imp.reset(); // eof, so make end iterator
           ^
/usr/local/include/boost/filesystem/directory.hpp:333:47: note: declared private here
  boost::intrusive_ptr< detail::dir_itr_imp > m_imp;
                                              ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2445:12: error: 'm_imp' is a private member of 'boost::filesystem::directory_iterator'
        it.m_imp->dir_entry.assign(p / filename, file_stat, symlink_file_stat);
           ^
/usr/local/include/boost/filesystem/directory.hpp:333:47: note: declared private here
  boost::intrusive_ptr< detail::dir_itr_imp > m_imp;
                                              ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2459:10: error: 'm_imp' is a private member of 'boost::filesystem::directory_iterator'
      it.m_imp.reset();
         ^
/usr/local/include/boost/filesystem/directory.hpp:333:47: note: declared private here
  boost::intrusive_ptr< detail::dir_itr_imp > m_imp;
                                              ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2534:27: error: out-of-line definition of 'push_directory' does not match any declaration in
      'boost::filesystem::detail::recur_dir_itr_imp'
  bool recur_dir_itr_imp::push_directory(system::error_code& ec) BOOST_NOEXCEPT
                          ^~~~~~~~~~~~~~
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2555:32: error: no member named 'top' in 'std::__1::vector<boost::filesystem::directory_iterator,
      std::__1::allocator<boost::filesystem::directory_iterator> >'
        symlink_stat = m_stack.top()->symlink_status(ec);
                       ~~~~~~~ ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2571:36: error: no member named 'top' in 'std::__1::vector<boost::filesystem::directory_iterator,
      std::__1::allocator<boost::filesystem::directory_iterator> >'
        file_status stat = m_stack.top()->status(ec);
                           ~~~~~~~ ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2575:41: error: no member named 'top' in 'std::__1::vector<boost::filesystem::directory_iterator,
      std::__1::allocator<boost::filesystem::directory_iterator> >'
        directory_iterator next(m_stack.top()->path(), ec);
                                ~~~~~~~ ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2579:19: error: no member named 'push' in 'std::__1::vector<boost::filesystem::directory_iterator,
      std::__1::allocator<boost::filesystem::directory_iterator> >'
          m_stack.push(std::move(next)); // may throw
          ~~~~~~~ ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2583:13: error: use of undeclared identifier 'm_level'
          ++m_level;
            ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2604:27: error: out-of-line definition of 'increment' does not match any declaration in 'boost::filesystem::detail::recur_dir_itr_imp'
  void recur_dir_itr_imp::increment(system::error_code* ec)
                          ^~~~~~~~~
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2637:40: error: no member named 'top' in 'std::__1::vector<boost::filesystem::directory_iterator,
      std::__1::allocator<boost::filesystem::directory_iterator> >'
      directory_iterator& it = m_stack.top();
                               ~~~~~~~ ^
/Users/xavier/.ycmd/cpp/BoostParts/libs/filesystem/src/operations.cpp:2644:15: error: no member named 'pop' in 'std::__1::vector<boost::filesystem::directory_iterator,
      std::__1::allocator<boost::filesystem::directory_iterator> >'
      m_stack.pop();
      ~~~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [BoostParts/CMakeFiles/BoostParts.dir/libs/filesystem/src/operations.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [BoostParts/CMakeFiles/BoostParts.dir/all] Error 2
make[1]: *** [ycm/CMakeFiles/ycm_core.dir/rule] Error 2
make: *** [ycm_core] Error 2
ERROR: the build failed.

NOTE: it is *highly* unlikely that this is a bug but rather
that this is a problem with the configuration of your system
or a missing dependency. Please carefully read CONTRIBUTING.md
and if you're sure that it is a bug, please raise an issue on the
issue tracker, including the entire output of this script
and the invocation line used to run it.

**Comment by bstaletic** [comment]
You system wide boost installation is getting in the way. Either add `--system-boost` or make sure cmake isn't reaching into `/usr/local/include/boost/filesystem`. This is likely caused by your system boobst and the bundled boost having mismatched versions.

**Comment by bananaspliff** [comment]
--system-boost solved the issue, thx

**Comment by cromwellryan** [comment]
`--system-boost` worked for me as well. 

> make sure cmake isn't reaching into /usr/local/include/boost/filesystem

Can you point me to information about how to do this? Just want to understand what this means and how to manage cmake and boost.

**Comment by bstaletic** [comment]
I don't really use macos, but `brew uninstall boost`, at least temporarily, until you recompile ycmd, should work.

**Comment by puremourning** [comment]
I can't repro. if someone can provide steps to repro with/without homebrew boost.

For reference, probably better to `brew unlink boost` to temporarily remove it rather than `brew uninstall`. You can then re-enable it with `brew link boost`
