### ISSUE TITLE
Can't install  rust-completer

### ISSUE THREAD

**Issue by shuaixr** [ycm-core/ycmd#1399]
Rust is installed now. Great!

To get started you need Cargo's bin directory (/tmp/rust_install_6beri2id/bin) 
in your PATH
environment variable.

To configure your current shell run source /tmp/rust_install_6beri2id/env
info: syncing channel updates for 'nightly-2019-09-05-armv7-unknown-linux-gnueabihf'
374.6 KiB / 374.6 KiB (100 %)  88.9 KiB/s in  6s ETA:  0s
info: latest update on 2019-09-05, rust version 1.39.0-nightly (c6e9c76c5 2019-09-04)
error: some components unavailable for download for channel nightly-2019-09-05: 'clippy', 'rustfmt'
If you require these components, please install and use the latest successful build version,
which you can find at <https://rust-lang.github.io/rustup-components-history>.

**Comment by bstaletic** [comment]
This looks like a network error on your end.

**Comment by puremourning** [comment]
Please include the entire output of the build command, including the invocation.

**Comment by shuaixr** [comment]
I fixed it by modifying line 92 of build.py
RUST_TOOLCHAIN = 'nightly-2018-12-06'

**Comment by shuaixr** [comment]
The compilation of arm and x86 is different
