### ISSUE TITLE
tsserver folder is empty and I get errors trying to build. 

### ISSUE THREAD

**Issue by ddaza** [ycm-core/ycmd#1402]
```bash
ERROR: folder tsserver in /Users/me/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party is empty; you probably forgot to run:
        git submodule update --init --recursive
```
I can `git submodule update --init --recursive` like 3 times and it looks like that folder is gone. 

Please help!

**Comment by bstaletic** [comment]
`tsserver` isn't a submodule. Remove the folder and try again.

**Comment by ddaza** [comment]
yeah.. that worked. I got in a weird state because I use a custom npm registry. 

Thanks
