### ISSUE TITLE
ImportError: [path-to]/.pyenv/versions/3.8.2/lib/python3.8/lib-dynload/_socket.cpython-38-arm-linux-gnueabihf.so: undefined symbol: PyFloat_Type

### ISSUE THREAD

**Issue by AUsernameWhichIsNotTaken** [ycm-core/ycmd#1408]
on a

    Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux

machine after successfully compiling the latest python, vim and ycm I get the above error message

Thanks a lot for your effort and time, Stephan

**Comment by bstaletic** [comment]
What's the output of the build script? What's in `PYTHON_USED_DURING_BUILDING` file?

**Comment by bstaletic** [comment]
Can you `import _socket` with your pyenv python? If not, python wasn't compiled correctly (with all necessary modules) compiled.

**Comment by AUsernameWhichIsNotTaken** [comment]
<pre>
$ cat third_party/ycmd/PYTHON_USED_DURING_BUILDING
[path-to]/.pyenv/versions/3.8.2/bin/python
</pre>

<pre>
$ python
Python 3.8.2 (default, Mar 12 2020, 14:28:26) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _socket
>>> 
</pre>
i.e. no problem

<pre>
goedel@raspberrypi:~/.vim/pack/bundle/start/YouCompleteMe $ python install.py >> ycm_build_script_out
</pre>

find attached, please.  Thank you!

[ycm_build_script_out.txt](https://github.com/ycm-core/ycmd/files/4326228/ycm_build_script_out.txt)

**Comment by puremourning** [comment]
can you confirm you built python with `--enable-shared` , like the FAQ says ?

https://github.com/ycm-core/YouCompleteMe/wiki/FAQ#i-get-fatal-python-error-pythreadstate_get-no-current-thread-on-startup

**Comment by AUsernameWhichIsNotTaken** [comment]
Yes
<pre>
export PYTHON_CONFIG_OPTS="--enable-shared"
pyenv install -fk 3.8.2
</pre>

**Comment by bstaletic** [comment]
In the ycmd directory, can you do `python -c 'import ycm_core`?

Are you seeing the "undefined symbol" error in vim itself? It could be the python that vim was linked against that is the problem. Can you do `:py3 import _socket`?

**Comment by AUsernameWhichIsNotTaken** [comment]
<pre>
~/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd $ python -c 'import ycm_core'
goedel@raspberrypi:~/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd 
</pre>

':py3' gives the same error, but there is only one python 3.8 on this machine, e.g. it is the same python 3.8 where I can import _socket at the repl.  Strange.

**Comment by puremourning** [comment]
so when you do `:py3 import _socket` in vim, you get the error , but not when you do `python -c 'import ycm_core'` ?

If so the problem is with your vim build, not YCM. how did you build vim ?

**Comment by AUsernameWhichIsNotTaken** [comment]
Yes, and
<pre>
./configure                     \
    --with-features=huge        \
    --enable-multibyte          \
    --enable-rubyinterp=yes     \
    --enable-python3interp=yes  \
    --with-python3-config-dir=$(python3-config --configdir) \
    --enable-perlinterp=yes     \
        --enable-luainterp=yes  \
    --enable-cscope             \
    --enable-gui=gtk2           \
    --prefix=/usr/local
make VIMRUNTIMEDIR=/usr/local/share/vim/vim82
sudo make install
<pre>

**Comment by puremourning** [comment]
Well, I'll be honest it's not obvious to me why that didn't work (then again, I never specify python3-config-dir when I build vim), but in any case, this is clearly not a ycmd issue (nor a YouCompleteMe one).

**Comment by bstaletic** [comment]
The YCM repo has 4 issues in which the problem comes down to "vim can't `py3 import _socket`". Try reading them in detail. The most interesting might be this comment: https://github.com/ycm-core/YouCompleteMe/issues/3580#issuecomment-589933447
