### ISSUE TITLE
Feature - Use proxy or ask for file's path

### ISSUE THREAD

**Issue by PeterlitsZo** [ycm-core/ycmd#1413]
I live in China and by the way the net do not work well when the build.py want to use `requests.get` to some file on the web.

I kown the `requests` can read shell's env variable to get the proxy's addrass and port, but I also hope you please can make build.py to can work with args like `--proxy=sock5://127.0.0.1:1080` or ask for file and let me download by some way else.

I do not kown a lot about git, but this task looks ok for me. If you like, I can help to with a new source file.

**Comment by bstaletic** [comment]
Hi. We've had similar issues reported previously. For example: https://github.com/ycm-core/ycmd/issues/1280

Mind telling us what exactly is causing you troubles?

**Comment by puremourning** [comment]
> I kown the requests can read shell's env variable to get the proxy's addrass and port, but I also hope you please can make build.py to can work with args like --proxy=sock5://127.0.0.1:1080

Why is that better than `env http_proxy=sock5://127.0.0.1:1080 ./install.py` ? It's a lot more work and testing for us, so i would rather not do it unless there's a good reason.

**Comment by PeterlitsZo** [comment]
I do love my country, but to be honest, because of [GFW](https://en.wikipedia.org/wiki/Great_Firewall), it is slowly to download some file your build.py need. I try to use ssr to communicate with proxy to get something I want, such as google's severve or github's file(we can get github but it is so slowly to get file). when I use wsl and I find your build.py need to download a lot of thing which is hard to get in China...... 

I have a way that use env variable `ALL_PROXY` or something like that to make `requests` get file by the proxy, but it will be better that has a thing to get the thing......

I kown that it's easy to add something but hard to remove. But if you still have interset to help me, then I think I can join you to touch the aim.

**Comment by PeterlitsZo** [comment]
> > I kown the requests can read shell's env variable to get the proxy's addrass and port, but I also hope you please can make build.py to can work with args like --proxy=sock5://127.0.0.1:1080
> 
> Why is that better than `env http_proxy=sock5://127.0.0.1:1080 ./install.py` ? It's a lot more work and testing for us, so i would rather not do it unless there's a good reason.

thanks for your advises!

it will be a nice way, I think.
by the way I just give my advice and it is true that there are some ways to make it.
I do response your thinking.

Thanks (again)

p.s. Are you a Chinese? I think I have watched your answer about `debugging on vim` on zhihu, is that you?

**Comment by puremourning** [comment]
> p.s. Are you a Chinese?

No, i'm British.

> I think I have watched your answer about debugging on vim on zhihu, is that you?

Not sure what you mean, but i did create [vimspector](https://github.com/puremourning/vimspector)

**Comment by PeterlitsZo** [comment]
> Not sure what you mean, but i did create vimspector

sorry about that, I just only see someone recommand your nice debugger. And it looks great really.

**Comment by hmgle** [comment]
I use the graftcp tool. `graftcp ./install.py` works fine for me.

**Comment by puremourning** [comment]
TIL graftcp. could be useful.

**Comment by PeterlitsZo** [comment]
nice idea. Thank you guy, `^_^`

**Comment by puremourning** [comment]
looks like there are sufficient workarounds for ensuring appropriate proxies are set up in the environment.

**Comment by PeterlitsZo** [comment]
You are right... now I use `proxychains4` on `WSL` and `socks proxy` on `Windows` to help me to access the resource.
