### ISSUE TITLE
Feature - A Progress Bar

### ISSUE THREAD

**Issue by PeterlitsZo** [ycm-core/ycmd#1420]
Hi, everyone.
Is it ok to add a process bar in `build.py` 's function `DownloadFileTo`?
you can make it easily, some infos like [this](https://stackoverflow.com/questions/15644964/python-progress-bar-and-downloads) can help you better.

p.s. setup program may be more useful if you can make this please...
`^_^`

**Comment by PeterlitsZo** [comment]
> Hi, everyone.
> Is it ok to add a process bar in `build.py` 's function `DownloadFileTo`?
> you can make it easily, some infos like [this](https://stackoverflow.com/questions/15644964/python-progress-bar-and-downloads) can help you better.
> 
> p.s. setup program may be more useful if you can make this please...
> `^_^`

![my code](https://i.imgur.com/gwFoyQm.jpg)
^
like this?

**Comment by puremourning** [comment]
PR welcome for this, but I don't think we're likely to work on it.

**Comment by PeterlitsZo** [comment]
Please forget about it... Now I do not think it is a good idea anymore.
