### ISSUE TITLE
[Feature request] Support gopls daemon mode

### ISSUE THREAD

**Issue by hmgle** [ycm-core/ycmd#1424]
Now the `vim-go` is already suported the shared gopls instance, it would be a nice performance improvement if `ycmd` could support talking to a daemon gopls.

Some relevant links:

- https://github.com/fatih/vim-go/issues/2760
- https://github.com/golang/tools/blob/master/gopls/doc/daemon.md
- https://github.com/golang/go/issues/34111
- https://github.com/fatih/vim-go/issues/2421

**Comment by hmgle** [comment]
I modified [this line](https://github.com/ycm-core/ycmd/blob/5241199e9637ed52d90bab1ba85b2f3f4fa43ed3/ycmd/completers/go/go_completer.py#L72) on my host and tested it. It showed a significant improvement in memory usage after running multiple vim instances.

```python
cmdline = [ self._gopls_path, '-remote=auto', '-logfile', self._stderr_file ]
```

**Comment by bstaletic** [comment]
Hi. Before diving into the docs, just a quick question. Besides being a new and probably buggy feature, are there any other downsides to `-remote=auto`?

**Comment by bstaletic** [comment]
Okay, this does look like a good idea, but does `-logfile` still work, or do we need `-remote.logfile`, or both?

**Comment by bstaletic** [comment]
@hmgle Could you check #1423 out?

**Comment by hmgle** [comment]
Oh, I just checked the #1423 PR. It adds a `gopls_args` for the user, and we can add a config `let g:ycm_gopls_args = "-remote=auto"` to enable this daemon mode.
LGTM

**Comment by yedamao** [comment]
> Oh, I just checked the #1423 PR. It adds a `gopls_args` for the user, and we can add a config `let g:ycm_gopls_args = ['-remote=auto']` to enable this daemon mode. LGTM

@hmgle  Thanks for your solution.
```
let g:ycm_gopls_args = ['-remote=auto']
let g:ycm_gopls_binary_path = [$GOPATH.'/gopls']
```
Seems like `ycmd` and `vim-go` should use the same `gopls` binary, the above config works for me.
