### ISSUE TITLE
Python GOTO not working due to incorrect python root

### ISSUE THREAD

**Issue by douglascook** [ycm-core/ycmd#1432]
Since the jedi upgrade in https://github.com/ycm-core/ycmd/pull/1423, `GoToType` and `GoToDefinition` have not been working for absolute imports from internal modules.

For example, with the directory structure below, using `GoToDefinition` on the first line of `importer.py` file, trying to jump to `import_me`, will fail with `Runtimerror: Can't jump to definition`.

```
ycm_test/
    .git/
    module_a/
        importer.py
        to_import.py
```

```python
# to_import.py
def import_me():
    return 'Imported!'
```

```python
# importer.py
from module_a.to_import import import_me

def run_it():
    import_me()
```

It looks like this is due to how the python root directory (project directory) is set when constructing the `JediProject` in [this method](https://github.com/ycm-core/ycmd/blob/2915514cbbf1215697662e2bc273b540a2abd868/ycmd/completers/python/python_completer.py#L125). In the debug info below you can see that the root is set to `module_a` rather than `ycm_test`, so the absolute import fails. The equivalent relative import works as expected.

Debug info:
```
Printing YouCompleteMe debug information...
-- Completion API: 1
-- Client logfile: /var/folders/h5/tb05l_f93cjggq8szdfsx0j400020g/T/ycm_gmxhkshj.log
-- Server Python interpreter: /usr/local/opt/python/bin/python3.7
-- Server Python version: 3.7.7
-- Server has Clang support compiled in: False
-- Clang version: None
-- No extra configuration file found
-- Python completer debug information:
--   Python interpreter: /Users/douglas/.virtualenvs/experiments/bin/python
--   Python root: /Users/douglas/projects/ycm_test/module_a
--   Python path: ['/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', '/Users/douglas/.virtualenvs/experiments/lib/
python3.7/site-packages']
--   Python version: 3.7.7
--   Jedi version: 0.17.0
--   Parso version: 0.7.0
-- Server running at: http://127.0.0.1:60219
-- Server process ID: 49884
-- Server logfiles:
--   /var/folders/h5/tb05l_f93cjggq8szdfsx0j400020g/T/ycmd_60219_stdout_0ajm5vvi.log
--   /var/folders/h5/tb05l_f93cjggq8szdfsx0j400020g/T/ycmd_60219_stderr_yvdojoss.log 
```

**Comment by bstaletic** [comment]
Right...

Since that update, jedi basically forced us to provide the project root, if we want to provide sys path as well.

My idea for that was:

1. Check if the user returned `project_directory` from `Settings()` in the user's `.ycm_extra_conf.py`.
2. If not, but there is a chosen `.ycm_extra_conf.py`, use the directory of the extra conf for the project root.
3. If there is no extra conf, just pick the directory of the opened file as the root.

I'm open for ideas how to discover the project root better. Maybe the fallback should be `os.path.join( os.path.dirname( filepath ), '..' )`...
Another possible caveat is the `2.` case, if it involves the global extra conf.

A workaround for this issue is just adding an empty extra conf in the root *and* loading it.

**Comment by bstaletic** [comment]
We could also look for `setup.py`, but what if there's no `setup.py`?

**Comment by douglascook** [comment]
The empty extra conf in the project root has got it working again, thanks for the quick reply.

In terms of how to better discover the root, one way could be to let `jedi` take care of it - if I don't pass a project and let jedi handle the project creation it sets the project directory as expected using [get_default_project](https://github.com/davidhalter/jedi/blob/8aaa8e00446f801c023bb4b056f51ac6f3d99e99/jedi/api/project.py#L365). 

So we could perhaps use `get_default_project` and pull the directory we need out of there in the case where none is specified in `.ycm_extra_conf.py`? This should be okay as long as the `Project` constructor doesn't end up having some side effects, it doesn't as far as I can see.

Leaving it to `jedi` would be more like how it worked before and would leave the responsibility with them to keep the heuristics they use updated. Not sure whether you prefer to do it yourself or leave the language-specific things to third party libs?

**Comment by bstaletic** [comment]
> In terms of how to better discover the root, one way could be to let `jedi` take care of it - if I don't pass a project and let jedi handle the project creation it sets the project directory as expected using get_default_project.

This sounds like a good idea. `get_default_project()` is also, apparently, [public API](https://jedi.readthedocs.io/en/latest/docs/api.html#jedi.get_default_project). So we should:

1. Check if the loaded extra conf returns `project_directory`.
2. Else, leave it to jedi.

> Leaving it to jedi would be more like how it worked before

That's a very good point. I'll make a PR later today.

**Comment by bstaletic** [comment]
Completely untested, because I'm really tired.

```diff
diff --git a/ycmd/completers/python/python_completer.py b/ycmd/completers/python/python_completer.py
index f53d136e..5e0f8cc0 100644
--- a/ycmd/completers/python/python_completer.py
+++ b/ycmd/completers/python/python_completer.py
@@ -143,7 +143,11 @@ class PythonCompleter( Completer ):
         settings[ 'project_directory' ] = os.path.dirname( module.__file__ )
       else:
         settings[ 'project_directory' ] = os.path.dirname( filepath )
-    return jedi.Project( settings[ 'project_directory' ],
+    project_directory = settings.get( 'project_directory' )
+    if not project_directory:
+      default_project = jedi.get_default_project( request_data[ 'filepath' ] )
+      project_directory = default_project._path
+    return jedi.Project( project_directory,
                          sys_path = settings[ 'sys_path' ],
                          environment_path = settings[ 'interpreter_path' ] )


```

**Comment by douglascook** [comment]
That threw an error when I tried it out on my test case:

```
NotADirectoryError: [Errno 20] Not a directory: '/Users/douglas/projects/ycm_test/module_a/importer.py/.jedi/project.json'
```

Jedi is looking for a project file for itself and expects `path` to be a directory rather than a file, so it hits the unexpected error when it tries to use `importer.py` as a dir.

Updating your patch to not pass anything to `get_default_project` means that jedi falls back on `os.getcwd()` and it works as expected. 

For the test case this either required opening vim from the project root, so cwd is correct, or adding a `.git` etc directory to the root so that the jedi heuristics pick it up.

**Comment by bstaletic** [comment]
What about changing `jedi.get_default_project( request_data[ 'filepath' ] )` to `jedi.get_default_project( os.path.dirname( request_data[ 'filepath' ] ) )`? Does that work better?

Or maybe `jedi.get_default_project( os.path.diname( os.path.abspath( request_data[ 'filepath' ] ) ) )`?
