### ISSUE TITLE
Extra confs can make `/message_poll` wrongfully return `False`

### ISSUE THREAD

**Issue by bstaletic** [ycm-core/ycmd#1433]
```python
def Settings(**kwargs):
    __import__("time").sleep(10)
```

Steps to repro:

1. Open a LSP supported file type.
2. Confirm loading the extra conf.
3. Wait ~10 seconds and confirm that `:YcmDebugInfo` says that the server is running.

Expected: Async diagnostics work.
Actual: Long poll, by now, has returned `False` and thus no new polling is being done. What's weird is that [this line](https://github.com/ycm-core/ycmd/blob/master/ycmd/handlers.py#L308) is the one causing the problem. This is the log, with extra debugging sprinkled in relevant places:

```
2020-05-06 21:36:43,551 - DEBUG - BOOM! No semantic completer exists for filetypes: ['']
2020-05-06 21:36:53,986 - DEBUG - No Settings function defined in /home/bstaletic/work/ycmd/ycmd/tests/rust/testdata/common/.ycm_extra_conf.py
2020-05-06 21:36:53,987 - DEBUG - Using path /home/bstaletic/work/ycmd/ycmd/tests/rust/testdata/common for extra_conf_dir
2020-05-06 21:36:53,987 - INFO - Starting rastCompleter: ['/usr/sbin/rust-analyzer']
```

**Comment by puremourning** [comment]
You sure it's not [this line](https://github.com/ycm-core/ycmd/blob/2915514cbbf1215697662e2bc273b540a2abd868/ycmd/completers/language_server/language_server_completer.py#L1644) which would make more sense.

**Comment by bstaletic** [comment]
You're probably right. I realized I didn't debug this properly last night.

The exception that I printed is polling for an empty filetype for the log file itself.

**Comment by bstaletic** [comment]
Actually, it's [this line](https://github.com/ycm-core/ycmd/blob/2915514cbbf1215697662e2bc273b540a2abd868/ycmd/completers/language_server/language_server_completer.py#L1639). Which makes a lot of sense.

@theli-ua As a dirty workaround, bump up [this timeout](https://github.com/ycm-core/ycmd/blob/master/ycmd/completers/completer.py#L26).

@puremourning Would another `threading.Event` be a solution? Something like

    # Return true either when the server is initialized, or before we even tried to start it.
    # If we tried to start the server and waiting for the `_initialize_event` still timed out,
    # assume that the server is borked and kill the message poll
    return self._initialize_event.is_set() or not self._start_server_event.is_set()

**Comment by bstaletic** [comment]
From a very brief testing, the following seems to work.

```diff
diff --git a/ycmd/completers/language_server/language_server_completer.py b/ycmd/completers/language_server/language_server_completer.py
index 62864ade..6b8a446c 100644
--- a/ycmd/completers/language_server/language_server_completer.py
+++ b/ycmd/completers/language_server/language_server_completer.py
@@ -871,6 +871,7 @@ class LanguageServerCompleter( Completer ):
     self._sync_type = 'Full'
     self._initialize_response = None
     self._initialize_event = threading.Event()
+    self._read_settings_event = threading.Event()
     self._on_initialize_complete_handlers = []
     self._server_capabilities = None
     self._is_completion_provider = False
@@ -1028,6 +1029,7 @@ class LanguageServerCompleter( Completer ):
          not self._initialize_event.is_set() ):
       self._initialize_response = None
       self._initialize_event.set()
+      self._read_settings_event.set()
 
 
   def _RestartServer( self, request_data, *args, **kwargs ):
@@ -1525,7 +1527,7 @@ class LanguageServerCompleter( Completer ):
     automatically in OnFileReadyToParse, but this may be used in completer
     subcommands that require restarting the underlying server."""
     self._extra_conf_dir = self._GetSettingsFromExtraConf( request_data )
-
+    self._read_settings_event.set()
     # Only attempt to start the server once. Set this after above call as it may
     # throw an exception
     self._server_started = True
@@ -1636,7 +1638,7 @@ class LanguageServerCompleter( Completer ):
 
           # If the timeout is hit waiting for the server to be ready, we return
           # False and kill the message poll.
-          return self._initialize_event.is_set()
+          return self._initialize_event.is_set() or not self._read_settings_event.is_set()
 
         if not self.GetConnection():
           # The server isn't running or something. Don't re-poll, as this will
```

**Comment by puremourning** [comment]
i dunno man, i feel like just fixing dodgy extra conf files that take 10s to run would be a more appropriate solution. there's no good reason for the initialisation exchange to take so long...

i mean we can increase the timeout, but i don't really think there's that much extra benefit to the extra complexity of another synchronisation point.

**Comment by bstaletic** [comment]
For the record, I tested with a whole minute of sleep and this patch worked, or at the very least, the diagnostics arrived asynchronously.

You might be right that this is too heavy a solution for the problem it is solving. Perhaps we should just bump the timeout a bit.

@theli-ua Can you tell us how long does your extra conf take?

**Comment by theli-ua** [comment]
I personally think that any code that relies on timing without synchronization is a bad practice though I am not insisting on you to fix that and as a user can just bump up the timeout. My use case is to collect certain environment related things like library path, cflags, etc from my workspace at startup and export them for things to work properly

**Comment by puremourning** [comment]
it's not that it relies on timing. It's a long-poll mechanism so it has a timeout where it returns to the client one of three responses:

* Failed - don't poll again
* No messages in the timeout window - send another poll in <x> ms
* Here are some messages - this is sent immediately a message is available - then poll again

What's happening is the first poll request is coming in and we're detecting that we haven't started the downstream server yet. so we allow up to one "long" poll timeout for the server to become ready. If the server isn't ready in that time it _probably_ failed to start ( this is _way_ more likely than this reported "it takes 10s to run my python to get a handful of settings" scenario). Telling the client to re-poll if the server died is pointless, so we return "Failed"

I think this is legit and the real problem is an extra conf `Settings` method which takes 10s. What's it even doing ?

**Comment by theli-ua** [comment]
>we haven't started the downstream server yet.

Sorry, which server are we talking about, ycmd?
If so, I agree, its fair to assume it should start in some timeout. Somehow I was under impression it was about LSP server which we know for sure if we have (not) started it yet, right?
