### ISSUE TITLE
there was SyntaxError: invalid syntax in

### ISSUE THREAD

**Issue by BigFishhhh** [ycm-core/ycmd#1448]
YouCompleteMe/third_party/ycmd/build.py", line 965
 print( *args, **kwargs )
           ^
SyntaxError: invalid syntax

should be **print( args, kwargs )**

**Comment by puremourning** [comment]
Please list steps to reproduce and full output along with invocation.

**Comment by bstaletic** [comment]
I'm pretty sure this is a problem with interpreter version.

**Comment by BigFishhhh** [comment]
@puremourning 

python install.py --clang-completer --system-libclang
  File "/k-vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 965
    print( *args, **kwargs )
           ^
SyntaxError: invalid syntax

**Comment by bstaletic** [comment]
What's your python version?

**Comment by BigFishhhh** [comment]
> I'm pretty sure this is a problem with interpreter version.

python2 or 3 should be print(args,kwargs) not print(*args, **kwargs)

**Comment by BigFishhhh** [comment]
> What's your python version?

python2 and python3.7+

**Comment by BigFishhhh** [comment]
you can test with :
def fun(*args,**kwargs):
    print('args=', args)
    print('kwargs=',kwargs)
fun(1,2,3,4,A='a',B='b',C='c',D='d')

**Comment by bstaletic** [comment]
Note that we don't want to print tuples and dictionaries, so printing `args` and `kwargs` would be wrong. We've dropped support for python2 almost half a year ago. Can you install python3 and compile with that?

**Comment by BigFishhhh** [comment]
> Note that we don't want to print tuples and dictionaries, so printing `args` and `kwargs` would be wrong. We've dropped support for python2 almost half a year ago. Can you install python3 and compile with that?

ok,python3 works,thx
