### ISSUE TITLE
Bug using ninja on Windows

### ISSUE THREAD

**Issue by Lothedr** [ycm-core/ycmd#1467]
Building ycm with ninja on Windows is failing due to unrecognized platform `x64`.

To reproduce bug, run `python build.py --ninja` on Windows.

Seems, that issue is [here](https://github.com/ycm-core/ycmd/blob/a24204e8382d0660a519f88b59c67026f453c085/build.py#L498). Since default value of `args.msvc` is 16, that `if` statment will be true when called in a way I mentioned before. I suppose, that additonal arguments `-A x64` should be only added if ninja is not selected as a build tool. Current workaround is to build ycmd with `python build.py --ninja --msvc 14`, since there `-A x64` won't be added to arguments.

**Comment by bstaletic** [comment]
Can you try changing [this line](https://github.com/ycm-core/ycmd/blob/a24204e8382d0660a519f88b59c67026f453c085/build.py#L498) to `if OnWindows() and args.msvc == 16 and not args.ninja:`?
