### ISSUE TITLE
gdscript + tcp_server branch

### ISSUE THREAD

**Issue by habamax** [ycm-core/ycmd#1470]
Hi, there is no "issues" in https://github.com/puremourning/ycmd-1/tree/tcp-server repo, so in case you need some input :)

I get smth working but not sure if everything is correct:

![image](https://user-images.githubusercontent.com/234774/92361588-41380480-f0f7-11ea-8004-015566005401.png)

Completion of gdscript specific functions doesn't work, although errors are highlighted and function is somehow known to ycm.

My setup (tried to figure it out from source code):

    let g:ycm_language_server =
    \ [
    \   {
    \     'name': 'gdscript',
    \     'connection_type': 'tcp',
    \     'port': 6008,
    \     'filetypes': [ 'gdscript' ]
    \   }
    \ ]

PS: coc provides following:

![image](https://user-images.githubusercontent.com/234774/92362313-801a8a00-f0f8-11ea-9cd3-b805cce0d86a.png)

![image](https://user-images.githubusercontent.com/234774/92362339-8a3c8880-f0f8-11ea-81fe-d8809060dcec.png)

**Comment by bstaletic** [comment]
Hi. Thanks for the feedback. When you say "completions don't work", have you checked the logs? Is there an assertion that is being triggered?

**Comment by habamax** [comment]
DebugInfo
```
Printing YouCompleteMe debug information...
-- Completion API: 1
-- Client logfile: C:\Users\maksim.kim\AppData\Local\Temp\ycm_fi4crz__.log
-- Server Python interpreter: C:\Users\maksim.kim\AppData\Local\Programs\Python\Python38\python.exe
-- Server Python version: 3.8.2
-- Server has Clang support compiled in: False
-- Clang version: None
-- No extra configuration file found
-- GenericLSP completer debug information:
--   gdscriptCompleter not running
--   gdscriptCompleter executable: None
--   No logfiles available
--   gdscriptCompleter Server State: Initialized
--   gdscriptCompleter Project Directory: C:\Users\maksim.kim\projects\godot\Save_The_Sheep
--   gdscriptCompleter Connection Type: tcp
--   gdscriptCompleter Settings: {}
--   gdscriptCompleter Port: 6008
-- Server running at: http://127.0.0.1:54528
-- Server process ID: 17892
-- Server logfiles:
--   C:\Users\maksim.kim\AppData\Local\Temp\ycmd_54528_stdout_c9iwhy2r.log
--   C:\Users\maksim.kim\AppData\Local\Temp\ycmd_54528_stderr__6f3hld4.log
```

stderr: http://vpaste.net/Z8CDB

**Comment by puremourning** [comment]
Thanks max. 

When I was testing it I found that the server was so slow It would timeout most completions. 

I was working on a mitigation but it’s not trivial.

**Comment by bstaletic** [comment]
> When I was testing it I found that the server was so slow It would timeout most completions.

I've come across this for a server or two as well.

**Comment by puremourning** [comment]
The way we do the resolve is at least partly (in this case mostly) to blame. 

I started implementing resolve properly. Some progress but it’s not working yet.

**Comment by habamax** [comment]
With the updated version I still can't complete a prints function and help popup is incomplete:

![image](https://user-images.githubusercontent.com/234774/92389204-53c73380-f121-11ea-9927-5c110aafb8f2.png)

although I get strange completion when inside a string:

![image](https://user-images.githubusercontent.com/234774/92389246-693c5d80-f121-11ea-813f-8943a9cb0d0f.png)

stderr: http://vpaste.net/NrrMy

**Comment by bstaletic** [comment]
We've merged the TCP/IP support. Is anything else missing here?

**Comment by habamax** [comment]
> We've merged the TCP/IP support. Is anything else missing here?

Nope, looks good so far.
