### ISSUE TITLE
Minor issue: Possibly outdated readme section regarding clangd support

### ISSUE THREAD

**Issue by anakimluke** [ycm-core/ycmd#1499]
On [line 101](https://github.com/ycm-core/ycmd/blame/master/README.md#L101) it's written:

    clangd support is currently experimental and changes in the near future might break backwards compatibility.

By reading the readme of the other youcompleteme repo I had the impression clangd was not experimental.

Is it still experimental? If not, then I'd suggest updating the file.

Thanks! I'm new to YCM and I'm figuring stuff out ;)

**Comment by bstaletic** [comment]
No, it's not considered experimental. That part just slipped through when we updated the README regarding clangd previously.

If you'd like to contribute, we can wait for you to send us a pull request. If not, that's fine too. Either way, thanks for notifying us.
