### ISSUE TITLE
Regex cannot be installed due to wrong file name

### ISSUE THREAD

**Issue by Cpointerz** [ycm-core/ycmd#1532]
ycmd/third_ Party / mrab-regex @ fa9def5 should be changed to regex@cc538bb

Otherwise, if you enter git submodule update -- init -- recursive during installation, it will get stuck indefinitely. Thank you. This is machine translation

**Comment by bstaletic** [comment]
`git submodule sync --recursive`

**Comment by bstaletic** [comment]
Closing due to lack of response.
