### ISSUE TITLE
Use latest stable typescript and minimize pull request work to keep updating typescript version

### ISSUE THREAD

**Issue by darcyparker** [ycm-core/ycmd#1541]
Often typescript is updated and it takes time for a pull request like this to be created/merged:
https://github.com/ycm-core/ycmd/pull/1512/files#diff-9dc0acc84bcb1dc4508fe953e3d1466f287b8f73acd226975158961ddf01baccR4

Would you be open to changing:
https://github.com/ycm-core/ycmd/blob/master/third_party/tsserver/package.json#L4 to be something like:

```json
  "dependencies": {
    "typescript": "^4.2.3"
  }
```
So that the latest `4.x` can be installed?

Or maybe there is a better way to do this?

**Comment by puremourning** [comment]
Unfortunately about 70% of the time when we update the downstream servers, it breaks something, so we pin versions that we know work, and pass our regression tests.

If you want to break with that and use a custom tsserver, you can [set this option](https://github.com/ycm-core/YouCompleteMe#the-gycm_tsserver_binary_path-option)

**Comment by darcyparker** [comment]
Very nice - I didn't know about that option. Thanks.
