### ISSUE TITLE
<filesystem>: compatibility with Termux on Android

### ISSUE THREAD

**Issue by xloem** [ycm-core/ycmd#1584]
Hi,

The terminal Termux app on Android unfortunately doesn't have the `<filesystem>` symbols exported: https://github.com/termux/termux-packages/issues/6275#issuecomment-899061044

Given `<filesystem>` is such a small part of this project, I was wondering if porting off of `<filesystem>` would be reasonable, to support users on Termux.

**Comment by bstaletic** [comment]
We have a `legacy-c++11` branch that uses Boost.Filesystem instead.

**Comment by bstaletic** [comment]
If you can figure out how to use `<filesystem>` with termux, as well as how to detect termux from cmake, we can make it work..

**Comment by xloem** [comment]
So this was my first search result for filesystem shim libraries: https://github.com/gulrak/filesystem

Apparently CMAKE_SYSTEM_NAME is supposed to be set to Android on Termux now, but it is considered better to check for individual features with something like CHECK_LIBRARY_EXISTS: https://github.com/termux/termux-packages/issues/151

**Comment by puremourning** [comment]
Yeah sorry you’ll have to stick with a legacy version until your OS supports our target requirements.

**Comment by xloem** [comment]
I'm not seeing a `legacy-c++11` branch in your project ...?

**Comment by xloem** [comment]
Given what you guys have said, I would propose checking for filesystem support in cmake, and also for ghc::filesystem at https://github.com/gulrak/filesystem, recommending installation of and falling back to the latter if the former is not found.

**Comment by bstaletic** [comment]
Huh... I could have sworn we tagged the last C++11 commit. Anyway, see https://github.com/ycm-core/YouCompleteMe/issues/3805#issuecomment-727643020

**Comment by xloem** [comment]
Thanks.  Looks like the branch might have gotten deleted: https://github.com/ycm-core/YouCompleteMe/issues/3805#issuecomment-784107020

**Comment by xloem** [comment]
Note: the comment you linked appears to have a typo, linking to ycmd/master rather than an old commit.  But I can also git blame the files.

**Comment by bstaletic** [comment]
> Looks like the branch might have gotten deleted

I think I'm going to blame @puremourning , so I wouldn't have to blame myself. We should tag that thing again.

> the comment you linked appears to have a typo, linking to ycmd/master 

It links to ycmd commits, because I was lazy and the change was, then, recent.

**Comment by puremourning** [comment]
> I think I'm going to blame @puremourning

The horror!

**Comment by bstaletic** [comment]
> The horror!

For 4 days, I was sure you had said "ho**n**or".

Anyway, I re-pushed `legacy-c++11` branch.

**Comment by xloem** [comment]
Thank you :-)

**Comment by puremourning** [comment]
> For 4 days, I was sure you had said "honor".

*honour
