### ISSUE TITLE
[Python format] How is the python file build.py foramtted?

### ISSUE THREAD

**Issue by ououmania** [ycm-core/ycmd#1620]
I am really sorry that this is not an issue. 
I really like the format style of build.py. 
Is there any vim plugin equivalence？
Thanks in advance.

**Comment by puremourning** [comment]
It's manually edited.

But we do have custom flake8 validators to check the style.

Take a look at our tox.ini for details of the config we use: https://github.com/ycm-core/ycmd/blob/master/tox.ini#L2
The custom flake8 plugins are: https://github.com/ycm-core/flake8-ycm

**Comment by ououmania** [comment]
> It's manually edited.
> 
> But we do have custom flake8 validators to check the style.
> 
> Take a look at our tox.ini for details of the config we use: https://github.com/ycm-core/ycmd/blob/master/tox.ini#L2 The custom flake8 plugins are: https://github.com/ycm-core/flake8-ycm

Got it. Thanks for the great effort.
