### ISSUE TITLE
The Hashes for AMD64 and i368 are swapped

### ISSUE THREAD

**Issue by gjake1337** [ycm-core/ycmd#1635]
On line 60 of CMakeLists.txt the hashes for Libclang amd64 and i386 are swapped around I think. The archive hash of the 64bit version is the same as the 32bit hash that shows up in the file.

how to recreate issue
1. compile VIM8 from ports on FreeBSD 13.0 AMD64
2. Install Plugged for vim
3. Add YCM too vim via Plug
4. Enter the .vim/plugged/YouCompleteMe directory
5. run python3.X install.py --all
6. The correct version of the Libclang archive is downloaded but it fails the hash.
7. Swapping the 32bit hash with the 64 bit hash in the CMakeLists.txt file allows it to continue.

**Comment by puremourning** [comment]
Thanks for the report! Yes this can happen due to pebkac in copy paste the hashes. Mind making a pR? I don't have a bsd system to test on right now.

**Comment by gjake1337** [comment]
Sorry for the late reply, I just got too it and submitted a pull request.

**Comment by puremourning** [comment]
I think your PR was merged right? Can we close this now?

We'll soon be updating to 15.0.1 anyway which will change the hashes, but also I'm afraid I have to drop support for BSD. The upstream binaries are often not available when we upgrade and the number of users on this platform is very small by comparison. BSD has always been "best efforts" and tbh I simply don't have the bandwidth or inclination to support it any longer.

I will still accept PRs which fix issues, etc. for BSD but as it's not tested by me or our CI and it's difficult to get upstream binaries, "built in" support will end with the next update to clang in #1658
