### ISSUE TITLE
Ruby Completions support

### ISSUE THREAD

**Issue by MuhammadAdam-CodeInterview** [ycm-core/ycmd#1638]
How can we add completions for Ruby ? If ycmd does not have it how can we add support for Ruby can you help us in this?

**Comment by puremourning** [comment]
Find a language server and use the language_server option. See https://github.com/ycm-core/lsp-examples#ruby

**Comment by MuhammadAdam-CodeInterview** [comment]
@puremourning thanks do we have to create ruby-completer class implentation in ycmd or by adding configuration it will work?

**Comment by puremourning** [comment]
just configuration.

**Comment by MuhammadAdam-CodeInterview** [comment]
@puremourning 
I have installed solargraph on Ubuntu and added below configuration in the YCMD (A code-completion & code-comprehension server)
`gem install solargraph`
`"language_server":` [{ "name": "solargraph", "cmdline": [ "solargraph", "stdio" ], "filetypes": [ "rb" ] }]`

When I try to get the completions this is how I am getting it:
a = []
`a. # <-- shows nothing`
`a.* # <-- shows menu`
`a.an # <-- shows menu`

why `a.` not giving any completions?
