### ISSUE TITLE
Regression in ycm_core rpath on Linux

### ISSUE THREAD

**Issue by dpacbach** [ycm-core/ycmd#1650]
Looks like commit a6c95a2ff7fd2600e37851a527ca01a972d41e0b might have broken dynamic loading of the ycm_core shared object on Linux when using a custom Clang installation.  This prevents YCM from working since when it tries to load that shared library it cannot locate libclang.so.13 and fails.  The commit description mentions that it is intended for mac, but it looks like it's just testing for "not MSVC", which includes Linux.

Specifically, when I update past this commit in my local copy and build YCM using my usual command:
```
$ EXTRA_CMAKE_ARGS="-DPATH_TO_LLVM_ROOT=/path/to/llvm" ./install.py --clang-completer
```

Then I get the following when inspecting the ycm_core binary:

```
$ cd ~/.vim/bundle/youcompleteme/third_party/ycmd
$ ldd ycm_core.cpython-38-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007ffea71e1000)
        libpython3.8.so.1.0 => /lib/x86_64-linux-gnu/libpython3.8.so.1.0 (0x00007f052c586000)
        libclang.so.13 => not found
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0526123000)
        ...
```
(note the "not found").  Even though I have the `libclang.so.13` symlink in the same folder.  When I revert that commit in my working copy and rebuild YCM with the same command, then it works fine, as before, since it has the correct rpath pointing directly to the libclang.so.13 in the same folder.

The commit mentioned above guards its logic with the following:
```cmake
if ( NOT MSVC )
  ...
endif ()
```

When I change it to the following it fixes the problem:
```cmake
if ( NOT MSVC AND NOT UNIX )
  ...
endif ()
```

@Chilledheart  FYI

**Comment by dpacbach** [comment]
Should mention that the "fix" that I proposed above (adding `AND NOT UNIX`) obviously fixes it for me because it disables that logic from running on my system, but I'm not sure if that would be the right general fix, will leave that up to the authors.

**Comment by puremourning** [comment]
I can't reproduce this. Please can you give steps to reproduce in a specific environment (e.g. container, vm) etc.

**Comment by puremourning** [comment]
Didn't llvm recently change their policy regarding soversions so that it only changes when libclang actually changes compatibility?

**Comment by puremourning** [comment]
Tbh my advice would be to ditch the legacy libclang completed and switch to clangd for tons more features and better performance etc etc. 

We will not be investing hardly any effort in the legacy mode.

**Comment by dpacbach** [comment]
Ok, yeah probably time to switch to clangd then.  Thx
