### ISSUE TITLE
Building gopls failed

### ISSUE THREAD

**Issue by Draven-1** [ycm-core/ycmd#1664]
ubuntu:~/. vim/plugged/YouCompleteMe$ python3 install.py --all
Generating ycmd build configuration...
OK
Compiling ycmd target: ycm_core...OK
Building regex module...OK
Building watchdog module...OK
Installing Omnisharp for C# support...OK
Building gopls for go completion... can't load package: package golang.org/x/tools/gopls@v0.9.4: can only use path@version syntax with 'go get'

FAILED
Trying legacy get get...OK
OK
Setting up Tern for JavaScript completion...OK
Installing rust-analyzer for Rust support...OK
Installing jdt. ls for Java support...OK
Setting up TSserver for TypeScript completion...OK
Setting up Clangd completer...OK

**Comment by puremourning** [comment]
Actual problem? No. 

> Trying legacy get get...OK

If you have an actual problem. State it.

**Comment by Draven-1** [comment]
> 
It works fine.

I didn't look very closely. I'm sorry

**Comment by Draven-1** [comment]
> Actual problem? No.
> 
> > Trying legacy get get...OK
> 
> If you have an actual problem. State it.
It works fine.

I didn't look very closely.  I'm sorry
