### ISSUE TITLE
ycmd requires Python >= 3.10.0

### ISSUE THREAD

**Issue by ChoppinBlockParty** [ycm-core/ycmd#1670]
I was building ycmd as usual
```
+ python3 build.py --clang-completer --go-completer --rust-completer --ts-completer
ycmd requires Python >= 3.10.0; your version of Python is 3.8.10 (default, Nov 14 2022, 12:59:47)
```
Why python 3.10 is a must for ycmd, many distributions yet do not have it? Is it possible to lower the version?

**Comment by puremourning** [comment]
To what?

**Comment by ChoppinBlockParty** [comment]
To 3.8 or 3.9?

**Comment by puremourning** [comment]
Based on what? What is the reasoning/logic?

Our support has always been ‘latest Ubuntu LTS’. I checked and 3.10 is the earliest current release that has bug fixes and will be supported for some time. The others will be end of life within about a year. 

https://devguide.python.org/versions/

I don’t have capacity to faff with dependencies keep breaking on 3.6 etc. I am willing to discuss a specific and reasonable policy but not ‘this is inconvenient for me so please change it’

**Comment by ChoppinBlockParty** [comment]
Ok, no problem. Thank you. I ended up building python 3.10 from source on Ubuntu20, script is [here](https://github.com/ChoppinBlockParty/Yuki-s-.files/blob/af18cc6fe8a8ecae118cf03c7ea5b374418cfca6/install-python.sh).
