### ISSUE TITLE
build.py builds ycm_core in Debug configuration

### ISSUE THREAD

**Issue by Chilledheart** [ycm-core/ycmd#1678]
Today I found out an issue that ycm_core built by build.py is in Debug configuration.

I copied the ycm_core.pyd from one computer to another found out ycmd failed to start by ImportError that some dlls are not installed. By inspecting the pyd binary with LLVM (aka llvm-readobj --coff-imports <path-to-pyd>), I found out it is linked to debug vc runtime that is vcruntime140_1d.dll and ucrtbased.dll which requires a full visual c++ installation. It must be a mistake because not only Debug configuration requires **non-redistributable** debug runtime but also **performance penalty** introduced by built-in assertions and zero compiler optimization.

I was looking into build.py's options with by-pass something like `-DCMAKE_BUILD_TYPE=Release` to cmake but only `--enable-debug` option. Is it that by-design? In my memory, cmake's BUILD_TYPE is `Debug` if not specified, which means `--enable-debug` is default.

**Comment by puremourning** [comment]
Using `./build.py --build-dir build/`, then I go into `cd build` and `make clean && make VERBOSE=1`, the following is the compilation command used:

```
cd /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/build/absl/absl/base && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DYCMD_CORE_VERSION=47 -DYCM_EXPORT="" -I/Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/absl -stdlib=libc++ -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=13.0 -fPIC -fvisibility=hidden -Wall -Wextra -Wcast-qual -Wconversion -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wformat-security -Wgnu-redeclared-enum -Winfinite-recursion -Wliteral-conversion -Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wself-assign -Wshadow -Wstring-conversion -Wtautological-overlap-compare -Wundef -Wuninitialized -Wunreachable-code -Wunused-comparison -Wunused-local-typedefs -Wunused-result -Wvla -Wwrite-strings -Wno-float-conversion -Wno-implicit-float-conversion -Wno-implicit-int-float-conversion -Wno-implicit-int-conversion -Wno-shorten-64-to-32 -Wno-sign-conversion -DNOMINMAX -std=c++17 -MD -MT absl/absl/base/CMakeFiles/absl_malloc_internal.dir/internal/low_level_alloc.cc.o -MF CMakeFiles/absl_malloc_internal.dir/internal/low_level_alloc.cc.o.d -o CMakeFiles/absl_malloc_internal.dir/internal/low_level_alloc.cc.o -c /Users/ben/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/absl/absl/base/internal/low_level_alloc.cc

**Comment by puremourning** [comment]
For the record, from our CMake files:

```cmake
# Force release build by default, speed is of the essence
if ( NOT CMAKE_BUILD_TYPE )
  set( CMAKE_BUILD_TYPE Release )
endif()


```

**Comment by Chilledheart** [comment]
Nice, in *nix build, there are never a debug runtime libraries. And I found "-O3" in your output and it shouldn't be an issue.

Did you try ninja generator as well? (you can use ``ninja -v`` to get verbose output)

I used ninja generator on a windows machine (on MSVC command line, namely ``x64 Native Tools Command Prompt for VS 2019`` , and VS sln generator is more complex to explain):
```
build.py --clang-completer --go-completer --ninja --build-dir build --verbose
```
and it generates command line such as (via ``ninja -t commands ycm_core``)
```
C:\PROGRA~2\MICROS~3\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DHAVE_SNPRINTF -DMS_WIN64 -DUNICODE -DYCMD_CORE_VERSION=47 -DYCM_EXPORT="" -D_UNICODE -IC:\Users\HKY\.vim\plugged\YouCompleteMe\third_party\ycmd\cpp\absl /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MP /bigobj /utf-8 /permissive- /Zc:__cplusplus /Zc:externConstexpr /Zc:inline /Zc:throwingNew /MDd /Zi /Ob0 /Od /RTC1 /W3 /DNOMINMAX /DWIN32_LEAN_AND_MEAN /D_CRT_SECURE_NO_WARNINGS /D_SCL_SECURE_NO_WARNINGS /D_ENABLE_EXTENDED_ALIGNED_STORAGE /bigobj /wd4005 /wd4068 /wd4180 /wd4244 /wd4267 /wd4503 /wd4800 -std:c++17 /showIncludes /Foabsl\absl\time\CMakeFiles\absl_time_zone.dir\internal\cctz\src\zone_info_source.cc.obj /Fdabsl\absl\time\CMakeFiles\absl_time_zone.dir\absl_time_zone.pdb /FS -c C:\Users\HKY\.vim\plugged\YouCompleteMe\third_party\ycmd\cpp\absl\absl\time\internal\cctz\src\zone_info_source.cc
```
from [ms document](https://learn.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-alphabetically?view=msvc-170), ``/Od`` means ``Disables optimization.``

**Comment by puremourning** [comment]
I can't even repro on windows

Wehn manually specifying `CMAKE_BUILD_TYPE=Release`:

```
C:\Users\Ben\vimfiles\bundle\YouCompleteMe-Clean\third_party\ycmd>dumpbin /dependents ycm_core.cp310-win_amd64.pyd
Microsoft (R) COFF/PE Dumper Version 14.31.31104.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file ycm_core.cp310-win_amd64.pyd

File Type: DLL

  Image has the following dependencies:

    python310.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    VCRUNTIME140_1.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    KERNEL32.dll

  Summary

        2000 .data
        4000 .pdata
      675000 .rdata
        1000 .reloc
        1000 .rsrc
       3B000 .text

C:\Users\Ben\vimfiles\bundle\YouCompleteMe-Clean\third_party\ycmd>     
```

Without:

```
C:\Users\Ben\vimfiles\bundle\YouCompleteMe-Clean\third_party\ycmd>dumpbin /dependents ycm_core.cp310-win_amd64.pyd
Microsoft (R) COFF/PE Dumper Version 14.31.31104.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file ycm_core.cp310-win_amd64.pyd

File Type: DLL

  Image has the following dependencies:

    python310.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    VCRUNTIME140_1.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    KERNEL32.dll

  Summary

        2000 .data
        4000 .pdata
      675000 .rdata
        1000 .reloc
        1000 .rsrc
       3B000 .text
```

Exactly the same?

**Comment by puremourning** [comment]
If the bug is in cmakes ninja generator, then you know what to do...

**Comment by Chilledheart** [comment]
> I can't even repro on windows
> 
> Wehn manually specifying `CMAKE_BUILD_TYPE=Release`:
> 
> ```
> C:\Users\Ben\vimfiles\bundle\YouCompleteMe-Clean\third_party\ycmd>dumpbin /dependents ycm_core.cp310-win_amd64.pyd
> Microsoft (R) COFF/PE Dumper Version 14.31.31104.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> 
> Dump of file ycm_core.cp310-win_amd64.pyd
> 
> File Type: DLL
> 
>   Image has the following dependencies:
> 
>     python310.dll
>     MSVCP140.dll
>     VCRUNTIME140.dll
>     VCRUNTIME140_1.dll
>     api-ms-win-crt-runtime-l1-1-0.dll
>     api-ms-win-crt-heap-l1-1-0.dll
>     api-ms-win-crt-string-l1-1-0.dll
>     api-ms-win-crt-math-l1-1-0.dll
>     api-ms-win-crt-stdio-l1-1-0.dll
>     api-ms-win-crt-filesystem-l1-1-0.dll
>     api-ms-win-crt-locale-l1-1-0.dll
>     KERNEL32.dll
> 
>   Summary
> 
>         2000 .data
>         4000 .pdata
>       675000 .rdata
>         1000 .reloc
>         1000 .rsrc
>        3B000 .text
> 
> C:\Users\Ben\vimfiles\bundle\YouCompleteMe-Clean\third_party\ycmd>     
> ```
> 
> Without:
> 
> ```
> C:\Users\Ben\vimfiles\bundle\YouCompleteMe-Clean\third_party\ycmd>dumpbin /dependents ycm_core.cp310-win_amd64.pyd
> Microsoft (R) COFF/PE Dumper Version 14.31.31104.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> 
> Dump of file ycm_core.cp310-win_amd64.pyd
> 
> File Type: DLL
> 
>   Image has the following dependencies:
> 
>     python310.dll
>     MSVCP140.dll
>     VCRUNTIME140.dll
>     VCRUNTIME140_1.dll
>     api-ms-win-crt-runtime-l1-1-0.dll
>     api-ms-win-crt-heap-l1-1-0.dll
>     api-ms-win-crt-string-l1-1-0.dll
>     api-ms-win-crt-math-l1-1-0.dll
>     api-ms-win-crt-stdio-l1-1-0.dll
>     api-ms-win-crt-filesystem-l1-1-0.dll
>     api-ms-win-crt-locale-l1-1-0.dll
>     KERNEL32.dll
> 
>   Summary
> 
>         2000 .data
>         4000 .pdata
>       675000 .rdata
>         1000 .reloc
>         1000 .rsrc
>        3B000 .text
> ```
> 
> Exactly the same?

That is expected behaviour.
When specifying ``CMAKE_BUILD_TYPE`` manually to ``Release``, ycm_core are compiled and linked correctly with release runtime. Without it, it won't work outside a VS installation.



> If the bug is in cmakes ninja generator, then you know what to do...

I guess it is not. Generator usually doesn't affect cmake internal variables.



> That said, I would happily merge a PR that sets CMAKE_BUILD_TYPE=Release in build.py if this fixes it for you.

Thanks. I would like to send it soon.

**Comment by puremourning** [comment]
> When specifying CMAKE_BUILD_TYPE manually to Release, ycm_core are compiled and linked correctly with release runtime. Without it, it won't work outside a VS installation.

But the dependencies are _the same_ suggesting to me that without changes, the built object is _not_ a debug build, i.e. there is no problem

**Comment by Chilledheart** [comment]
It seems it is a bug with Ninja generator only. I managed to add this below line to ``cpp/CMakeLists.txt`` but it never triggers with ``--ninja`` option:
```
# Force release build by default, speed is of the essence
if ( NOT CMAKE_BUILD_TYPE )
  message(FATAL_ERROR "Set to Release now")
  set( CMAKE_BUILD_TYPE Release )
endif()
```

BTW for VS sln generator, it requires pass by ``--config Release`` to ``cmake --build`` command which is done in GetCMakeBuildConfiguration. So it should be a problem for VS sln generator.
