### ISSUE TITLE
YCMD not starting

### ISSUE THREAD

**Issue by pedricm** [ycm-core/ycmd#1683]
Hey guys I am trying to use ycmd server in Geany, but whenever I try this message appears to me: 
"17:28:34: ycmd startup failed: ycmd server has gone AWOL!", I have installed ycmd via the source code and via vundle, but it doesn't work eather way.

**Comment by puremourning** [comment]
> ycmd server in Geany

I have no idea what this means, sorry. Please can you explain exactly what your use case is, exactly what you did and exactly what the output was.

> ycmd server has gone AWOL

I have no idea what would produce this message, but YCM doesn't and I don't think anything in ycmd would, so I guess this is output from your ycmd client.

---

For general help with ycmd startup, there are some troubleshooting guides here for the YouCompleteMe client, many of which should apply even if not using YCM:  https://github.com/ycm-core/YouCompleteMe/wiki/Troubleshooting-steps-for-ycmd-server-SHUT-DOWN

If that gets ycmd starting up for you (manually, from the command line), please contact the author of your ycmd client (Geany?!). If not, please (at least):

- full steps to reproduce (what you did)
- full output of ycmd logs with debug log enabled (what actually happened) - `server_log_level` should be `debug` in the options file.
- python version
- output of the `build.py` with `--verbose`
