### ISSUE TITLE
Support Unicode 15.1 new GB9c break rule

### ISSUE THREAD

**Issue by DonKult** [ycm-core/ycmd#1718]
ycmd embeds its unicode support files and tests (currently for version 13), but a script (`update_unicode.py`) is provided to update to the latest unicode version. This used to work to upgrade to version 14, but doesn't anymore with 15. The tests fail for example with:
```
[ RUN      ] UnicodeTest/WordTest.BreakIntoCharacters/1186
./cpp/ycm/tests/Word_test.cpp:60: Failure
Value of: Word( word_.text_ ).Characters()
Expected: { *{ "\xE0\xA4\x95\xE0\xA5\x8D\xE0\xA5\x8D\xE0\xA4\xA4"
    As Text: "कत", "\xE0\xA4\x95\xE0\xA4\xA4"
    As Text: "कत", "\xE0\xA4\x95\xE0\xA5\x8D\xE0\xA5\x8D\xE0\xA4\xA4"
    As Text: "कत", "\xE0\xA4\x95\xE0\xA5\x8D\xE0\xA5\x8D\xE0\xA4\xA4"
    As Text: "कत", false, true, false, false } }
  Actual: { *{ "\xE0\xA4\x95\xE0\xA5\x8D\xE0\xA5\x8D"
    As Text: "क", "\xE0\xA4\x95"
    As Text: "क", "\xE0\xA4\x95\xE0\xA5\x8D\xE0\xA5\x8D"
    As Text: "क", "\xE0\xA4\x95\xE0\xA5\x8D\xE0\xA5\x8D"
    As Text: "क्, false, true, false, false }, *{ "\xE0\xA4\xA4"
    As Text: "त", "\xE0\xA4\xA4"
    As Text: "त", "\xE0\xA4\xA4"
    As Text: "त", "\xE0\xA4\xA4"
    As Text: "त", true, true, false, false } }

[  FAILED  ] UnicodeTest/WordTest.BreakIntoCharacters/1186, where GetParam() = { "\xE0\xA4\x95\xE0\xA5\x8D\xE0\xA5\x8D\xE0\xA4\xA4"
    As Text: "कत", { "\xE0\xA4\x95\xE0\xA5\x8D\xE0\xA5\x8D\xE0\xA4\xA4"
    As Text: "कत" } (0 ms)
```

The reason is that 15.1 introduces a new rule for (not) breaking: [GB9c](https://unicode.org/reports/tr29/#GB9c) and of course the new tests exercising this rule fail now.

Prior art implementing this rule elsewhere: https://github.com/JuliaStrings/utf8proc/pull/253

Would be nice if support for newer Unicode standards could be added to ycmd.

**Comment by puremourning** [comment]
PR welcome.

**Comment by bstaletic** [comment]
I have recently tried doing a naive upgrade to the latest unicode standard, but have seen that the tests are failing.

> The reason is that 15.1 introduces a new rule for (not) breaking: [GB9c](https://unicode.org/reports/tr29/#GB9c) and of course the new tests exercising this rule fail now.

Thanks for tracking this down. I have stopped at the previous step, because I was busy. In case you *do* want to contribute:

https://github.com/ycm-core/ycmd/blob/master/cpp/ycm/Word.cpp#L31

**Comment by bstaletic** [comment]
@DonKult I am afraid I am having troubles understanding the new rule. Up to now [the boundary rules](https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundary_Rules) table contained only break properties that were explained in [the values table](https://unicode.org/reports/tr29/#Grapheme_Cluster_Break_Property_Values). Now that [GB9c](https://unicode.org/reports/tr29/#GB9c) is added, it talks about "Indic_Conjunct_Break" (`InCB`), but I don't see it defined anywhere.

On top of that, `InCB` is not mentioned in [the break property data](https://www.unicode.org/Public/UCD/latest/ucd/auxiliary/GraphemeBreakProperty.txt) either.

**Comment by bstaletic** [comment]
We have merged the update.
