### ISSUE TITLE
ycm for new gcc version in centos stream 8?

### ISSUE THREAD

**Issue by bethebest0622** [ycm-core/ycmd#1732]
ycm worked very well in my centos stream 8.

but recently i want to use c++20, so i install the new gcc toolset.

the new gcc is on:  `/opt/rh/gcc-toolset-13/root/usr/include/c++/13`

i added this path into `.ycm_extra_conf.py `

then i found the whole projected was full of error, one of the error is about std::string:

`member reference base type 'const std::string' (aka 'const int') is not a structure or union`

could you help on this? how can i got the new gcc ycm support?

**Comment by bstaletic** [comment]
Next time, fill out the issue template, as it would have had you fill in the relevant info. We still need the debug logs, the `:YcmDebugInfo` and possibly more that I am not thinking of right now.

> the new gcc is on: /opt/rh/gcc-toolset-13/root/usr/include/c++/13
i added this path into .ycm_extra_conf.py 

That does not sound right. C++ compilers do not have a single system include path, so I bet your system headers are getting mixed up, but... debug info and logs.

**Comment by puremourning** [comment]
You probably need to add `--gcc-toolchain /opt/rh/gcc-toolset-13/root/usr` to your flags. 

Closing because not a ycmd bug.
