### ISSUE TITLE
Deprecation Warning when compiling on Linux using Python >= 3.13

### ISSUE THREAD

**Issue by PhilippeGouin** [ycm-core/ycmd#1776]
### The warning
Output of the command `python3 install.py --clangd-completer`:
```
...
Setting up Clangd completer.../(path)/YouCompleteMe/third_party/ycmd/build.py:1235: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  package_tar.extractall( CLANGD_OUTPUT_DIR )
OK
```

### Configuration
Linux (Fedora 41) with Python 3.13.1 (regarding the documentation, Python > 3.12 should issue the warning)

### Python relative documentation
Changed in version 3.12: Archives are extracted using a [filter](https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter), which makes it possible to either limit surprising/dangerous features, or to acknowledge that they are expected and the archive is fully trusted. By default, archives are fully trusted, but this default is deprecated and slated to change in Python 3.14.

### A fix
```diff
--- a/build.py
+++ b/build.py
@@ -1232,7 +1232,7 @@ def DownloadClangd( printer ):

   printer( f"Extracting Clangd to { CLANGD_OUTPUT_DIR }..." )
   with tarfile.open( file_name ) as package_tar:
-    package_tar.extractall( CLANGD_OUTPUT_DIR )
+    package_tar.extractall( CLANGD_OUTPUT_DIR, filter='tar' )

   printer( "Done installing Clangd" )
```

**Comment by bstaletic** [comment]
We're aware and the upcoming default is a better choice. However, we still support python 3.9.

I considered making some awkward checks for version to decide whether to use `filter='data'` or not.
In the end, I thought it would be easier to just let python do its thing at the cost of the deprecation warning.

**Comment by PhilippeGouin** [comment]
OK I get your point and I'm closing the issue. Happy 🎅🏼
