### ISSUE TITLE
C/C++: server command to get all currently defined preprocessor macros

### ISSUE THREAD

**Issue by deb0ch** [ycm-core/ycmd#692]
Is there a way of obtaining all currently defined preprocessor macros for a given C/C++ file, along with their values ? If not, would it be possible / easy to implement ?

I don't know if there is a libclang function for this, or if such a thing is already possible using some trick on a completion request.

It would allow a reliable use of Emacs's [hide-ifdef](https://www.emacswiki.org/emacs/HideIfDef) feature. I don't know if other editors have such a feature, but at least this would make it possible.

It might also have some uses that I haven't thought of.

**Comment by vheon** [comment]
I think that the definition of macros is actually something that is specified when you compile the TU hence they should be in the flags for that TU that the user provide to ycmd though `.ycm_extra_conf.py` or a compilation database on its behalf. So you actually already know if a macro is defined. Am I missing something?

**Comment by deb0ch** [comment]
The definition of some macros *can* be specified from the command line, although most of the time they reside in the code.

Moreover, some macros are defined conditionally or even constructed at compile-time, and it will also depend on the order in which the headers are included (and not all headers in the directories specified on the command line are included in each file). 

So to get a list of preprocessor macros and their values we would basically need to reimplement a C preprocessor, and in the future keep it up to date with the evolution of the C standards.

Pretty tedious, unless we can use the one that is already implemented and kept up-to-date in libclang :smile_cat: 

This is why I thought it would be nice to have it implemented in `ycmd` :smiley_cat:

**Comment by puremourning** [comment]
I think @davits for provides unparsed ranges. This can be used to implement equivalent functionality to the emacs function and when use din combination with his YCM fork in Vim. 

Eventually, we didn't merge the feature from @davits, so I don't expect we would implement an equivalent. @Valloric, @micbou, @vheon would you agree?

**Comment by deb0ch** [comment]
I'm sory, but I didn't get what you mean by "unparsed ranges" ? By "the emacs function", are you referring to `hide-ifdefs` ?

How is @davits' fork related to preprocessor macros ?

I'm not 100% sure I expressed myself very clearly about this functionality, maybe an example would be better.

For instance, if you have:

``` c
#if FOO
# define BAR 42
#else
# define BAR 32816
# define BLAH "yolo"
# define YOLO __GNU_WHATEVER_SOURCE
#endif

#define TOKENPASTE(x, y) x ## y
#define TOKENPASTE2(x, y) TOKENPASTE(x, y)
#define UNIQUE static void TOKENPASTE2(Unique_, __LINE__)(void) {}

// whatever corner case of preprocessor macros expansion
```
with FOO defined (or not) in an included header or from the command line.

The functionality that I'm talking about is a server request that will tell me what is defined to what value.

Knowing it would be useful from the editor, for instance for Emacs' `hide-ifdef`, and I don't see any place that would make more sense to implement that in than `ycmd`.

**Comment by puremourning** [comment]
In the mentioned fork, the server returns skipped ranges. See for info http://clang.llvm.org/doxygen/group__CINDEX__LOCATIONS.html#gae27bc89151459aeb94e0fb7aa0552d35. That is ranges of code that were skipped due to ifdefs.

 I don't believe we can do what you're asking.

**Comment by puremourning** [comment]
Closing as this is very old and unlikely to be possible without changes to LSP
