### ISSUE TITLE
Add GoToReferences to Clang completer

### ISSUE THREAD

**Issue by glymehrvrd** [ycm-core/ycmd#86]
I noticed ycmd returned variable completion proposals without their type, I think variable type hint is important. And can ycmd add the feature that finds out all locations an variable/function appears, so variable/function renaming can be implemented.

**Comment by puremourning** [comment]
I currently have a local modification which adds a YcmCompleter GetType command to return the type of c/c++ identifier under the cursor. This is useful for c++11 and the use of auto. Would that be helpful?

Regarding refactoring, I did take a look, and clang does have some support for this, but never got round to following it up. I'll maybe take another look.

**Comment by glymehrvrd** [comment]
@puremourning, that is excellent. Could you publish your modified ycmd on github, and make a pull request to this official repository? I think this will be very helpful.

**Comment by puremourning** [comment]
@glymehrvrd sure i will look into it. If all else fails, i can provide diffs. Have to work out how this git submodule lark actually works... :) *to google*

**Comment by Valloric** [comment]
@puremourning I was thinking of adding a new YCM completer subcommand `EchoType` (or similar) for the clang_completer that would echo out the type of the variable to Vim's status area. To implement this, ycmd will need exactly the feature you seem to have implemented.

If you could wrap this up in a pull request and add some tests for it, it would be merged in.

**Comment by puremourning** [comment]
@Valloric yep that's exactly what my changes to ccmd and YouCompleteMe do. I will push it asap.

**Comment by puremourning** [comment]
I'm having trouble running the tests (i don't have flake8 and i am unable to install it on the system where this is developed). It might take me quite some time, so in the meantime i've pushed the changes to puremourning/ycmd and puremourning/YouCompleteMe in these commits in case anyone wants it sooner:

https://github.com/puremourning/ycmd-1/commit/bf67100def9e547a563efdf6bbee329b28bc5679
https://github.com/puremourning/YouCompleteMe/commit/cdfee323460afdb037410e8af0fbb3c5fbb18db7

**Comment by puremourning** [comment]
Pull request submitted. https://github.com/Valloric/ycmd/pull/87

**Comment by ivankoster** [comment]
I'm interested in particular in the find-all-references functionality for c/c++.
What is needed for this? How will YCMD know in which files to search for all references? Will it need some kind of notion of project?

**Comment by puremourning** [comment]
@ivankoster ycmd can do anything you can do with the [`libclang` API](http://clang.llvm.org/doxygen/group__CINDEX.html). This means that it _would_ be possible to find all references to a particular identifier (e.g. starting with [this](http://clang.llvm.org/doxygen/group__CINDEX__HIGH.html#gaa8524d179bc3668d215d326d332df97b)).

Right now, however, ycmd would only be able to find references within buffers that are open in the client's editor, as this is all we pass to `libclang` when parsing/indexing. This is the same restriction that exists for  the `GoToDefinition`/`GoToDeclaration` etc. completer subcommands.

There is talk of integrating (or providing integration with) some sort of project/indexing support into `libclang` but that's unsurprisingly some way off. The biggest challenge is that there's just no standard for c++ 'projects' and so it's very difficult to have a generic way of describing the relationship or structure of your code.

**Comment by daedric** [comment]
>There is talk of integrating (or providing integration with) some sort of project/indexing support into libclang but that's unsurprisingly some way off. The biggest challenge is that there's just no standard for c++ 'projects' and so it's very difficult to have a generic way of describing the relationship or structure of your code.

When a compilation database is given would it be doable ? That the closest thing in my mind to a standard way of representing a C++ project.
I guess with a such a feature a lot problems arise like what do you keep in memory, how long, etc.

I'll try to save up some time to dig a bit around this issue.

**Comment by puremourning** [comment]
Even with a compilation database, you have the problem that without an index you have to compile the entire source tree just to find references. On many users' codebases, this can take _significant_ time. 

Take a look, for example at [rtags](https://github.com/Andersbakken/rtags). I've never been successful at getting it to work, but ymmv.

**Comment by jinjiazhang** [comment]
http://eli.thegreenplace.net/2011/07/03/parsing-c-in-python-with-clang/
I think libclang exposed this feature(find all References), but I don't know how to use it.

**Comment by quicknir** [comment]
@ivankoster Just happened to come across this. Fwiw I have rtags setup and it handles this sort of thing perfectly. I've recently discovered ycmd is quite a bit faster for functionality that relates to the current TU; i.e. autocompletion + flycheck. rtags however has an excellent database, and does go to definition, find references, inheritance hierarchies, etc, quickly and accurately.

The nice thing is that they both run off of a compile_commands.json. So once you resolve a few quirks in each, at least you can reuse any effort you put into producing/updating your compilation database.

**Comment by ivankoster** [comment]
@quicknir Thanks, rtags was indeed on my radar too. Unfortunately I do not use a compilation database. My build system itself can output the build flags for a given file pretty quickly, so that is what i use in .ycm-extra-conf file. In the future i might look at rtags.

**Comment by bstaletic** [comment]
`GoToReferences` is available in the clangd completer with indexing enabled. Since the plan is to eventually migrate to clangd, this won't be implemented in the old libclang completer.

With clangd 8 `-background-index` is needed in the`clangd_args` user option.

**Comment by puremourning** [comment]
Closing as clangd provides this functionally.
