### ISSUE TITLE
CMake: server mode support

### ISSUE THREAD

**Issue by ghost** [ycm-core/ycmd#878]
According to [this mailing list response](https://cmake.org/pipermail/cmake-developers/2017-November/030480.html) by Brad King, one of the core CMake developers,
> `compile_commands.json` was a hack to support clang-tidy and similar tools
and was never meant to be a general way to get information.  It has largely
been superseded by dedicated support for specific tools plus the server mode
query information in a more structured way.

Are there any plans for the server mode support [and eventual superseding of `compile_commands.json`]? Server mode was first introduced in 3.7.1 30th Nov 2016 (almost a year ago). I would love to see it as `compile_commands.json` has its disadvantages.

**Comment by puremourning** [comment]
> Are there any plans for the server mode support [and eventual superseding of compile_commands.json]? 

No there are not any such plans. compilation databases are convenient, but i suppose in theory you could write a ycm extra conf file which spoke to a cmake server. or any other server for that matter.

**Comment by puremourning** [comment]
It's highly unlikely that we will ever implement this, as it is too tied to CMake and therefore not general.
